<?php
/*
 * Copyright (c) 2025 AltumCode (https://altumcode.com/)
 *
 * This software is licensed exclusively by AltumCode and is sold only via https://altumcode.com/.
 * Unauthorized distribution, modification, or use of this software without a valid license is not permitted and may be subject to applicable legal actions.
 *
 * 🌍 View all other existing AltumCode projects via https://altumcode.com/
 * 📧 Get in touch for support or general queries via https://altumcode.com/contact
 * 📤 Download the latest version via https://altumcode.com/downloads
 *
 * 🐦 X/Twitter: https://x.com/AltumCode
 * 📘 Facebook: https://facebook.com/altumcode
 * 📸 Instagram: https://instagram.com/altumcode
 */

return [
    'direction' => 'ltr',

    'global.submit' => '提交',
    'global.create' => '创建',
    'global.delete' => '删除',
    'global.edit' => '编辑',
    'global.view' => '查看',
    'global.duplicate' => '复制',
    'global.transfer' => '转移',
    'global.reset' => '重置',
    'global.share' => '分享',
    'global.share_via' => '通过 %s 分享',
    'global.cancel' => '取消',
    'global.update' => '更新',
    'global.enable' => '启用',
    'global.hidden' => '隐藏',
    'global.login' => '登录',
    'global.language' => '语言',
    'global.choose_language' => '选择语言',
    'global.choose_currency' => '选择货币',
    'global.theme_style' => '切换到 %s (CMD/CTRL + I)',
    'global.theme_style_light' => '浅色模式',
    'global.theme_style_dark' => '深色模式',
    'global.close' => '关闭',
    'global.search' => '搜索',
    'global.no_data' => '无可用数据',
    'global.unknown' => '未知',
    'global.none' => '无',
    'global.yes' => '是',
    'global.no' => '否',
    'global.status' => '状态',
    'global.active' => '活跃',
    'global.disabled' => '禁用',
    'global.all' => '全部',
    'global.order' => '排序',
    'global.download' => '下载',
    'global.download_as' => '下载为 %s',
    'global.export' => '导出',
    'global.export_to' => '导出到 %s',
    'global.captcha_placeholder' => '验证码文本',
    'global.loading' => '加载中..',
    'global.view_more' => '查看更多',
    'global.view_x_more' => '查看另外 %s 条..',
    'global.clipboard_copy' => '复制到剪贴板',
    'global.clipboard_copied' => '已复制！',
    'global.terms_and_conditions' => '条款和条件',
    'global.privacy_policy' => '隐私政策',
    'global.delete_file' => '删除已上传的文件',
    'global.remove_selected_file' => '移除选定的文件',
    'global.bulk_actions' => '批量操作',
    'global.unlimited' => '无限制',
    'global.duplicated' => '已复制',
    'global.datetime' => '创建于',
    'global.last_datetime' => '更新于',
    'global.datetime_tooltip' => '创建于 %s',
    'global.last_datetime_tooltip' => '更新于 %s',
    'global.device' => '设备',
    'global.device.desktop' => '桌面设备',
    'global.device.tablet' => '平板电脑',
    'global.device.mobile' => '移动设备',
    'global.continent' => '大洲',
    'global.continents' => '大洲',
    'global.country' => '国家',
    'global.countries' => '国家',
    'global.city' => '城市',
    'global.cities' => '城市',
    'global.os_name' => '操作系统',
    'global.browser_name' => '浏览器',
    'global.browser_language' => '浏览器语言',
    'global.ip' => 'IP',
    'global.name' => '名称',
    'global.description' => '描述',
    'global.title' => '标题',
    'global.email' => '电子邮件',
    'global.email_placeholder' => 'hello@example.com',
    'global.password' => '密码',
    'global.user' => '用户',
    'global.image' => '图片',
    'global.icon' => '图标',
    'global.icon_placeholder' => 'fas fa-bolt',
    'global.icon_help' => '<a href="https://fontawesome.com/search?o=r&m=free" target="_blank">FontAwesome</a> 图标类。',
    'global.url' => 'URL',
    'global.url_placeholder' => 'https://example.com/',
    'global.url_slug_placeholder' => 'example',
    'global.host' => '主机',
    'global.host_placeholder' => 'example.com',
    'global.admin_impersonate_user_help' => '以...身份登录',
    'global.admin_impersonate_user_logout' => '退出',
    'global.spintax_help' => '您也可以使用Spintax格式，例如：<code>{你好|嗨|喂}</code> 来随机化单词或短语。',
    'global.update_x' => '编辑 %s',
    'global.mb' => 'MB',
    'global.details' => '详情',
    'global.type' => '类型',
    'global.view_all' => '查看全部',
    'global.select_all' => '全选',
    'global.deselect_all' => '取消全选',
    'global.show' => '显示',
    'global.hide' => '隐藏',
    'global.chart_help' => '图表每 %1$s 小时自动刷新。数据来自过去 %2$s 天。',
    'global.id' => '条目编号 (ID)',
    'global.variables' => '您可以使用以下动态变量：%s。',
    'global.translate' => '翻译',
    'global.scroll_top' => '滚动到顶部',
    'global.scroll_bottom' => '滚动到底部',
    'global.no_chart_data' => '无可用数据',
    'global.no_chart_data_help' => '没有足够的数据来生成图表。',
    'global.image_error' => '图片错误',
    'global.spotlight.search_placeholder' => '🔎 搜索并跳转到页面...',
    'global.spotlight.tooltip' => '聚光灯搜索 (CMD/CTRL + K)',
    'global.drag_and_drop' => '拖放以重新排序',
    'global.crop' => '裁剪图片',
    'global.crop_selection' => '裁剪选区',
    'global.no_crop' => '不裁剪继续',

    'global.info_message.user_plan_is_expired' => '您当前的计划已过期，您的访问权限现已受限。',
    'global.info_message.team_not_allowed' => '您必须退出当前团队才能访问此功能。',
    'global.info_message.plan_feature_no_access' => '您当前的计划不允许您访问此功能。',
    'global.info_message.plan_upgrade' => '升级您的计划 🔐',
    'global.info_message.plan_feature_limit' => '您已超出当前计划的限制。',
    'global.info_message.plan_feature_limit_info' => '已使用 %1$s / %2$s <br /> 剩余 %3$s',

    'global.success_message.create1' => '%s 已成功创建。',
    'global.success_message.create2' => '创建成功。',
    'global.success_message.update1' => '%s 已成功更新。',
    'global.success_message.update2' => '更新成功。',
    'global.success_message.delete1' => '%s 已成功删除。',
    'global.success_message.delete2' => '删除成功。',

    'global.error_message.directory_not_writable' => '目录 <strong>%s</strong> 不可写。请设置 CHMOD 权限，以便可以写入此文件夹。',
    'global.error_message.file_not_writable' => '文件 <strong>%s</strong> 不可写。请设置 CHMOD 权限，以便可以写入此文件。',
    'global.error_message.empty_fields' => '您必须填写所有必填字段。',
    'global.error_message.empty_field' => '此字段为必填项，您必须填写。',
    'global.error_message.invalid_file_type' => '您不允许上传此类型的文件。',
    'global.error_message.file_upload' => '上传文件时发生错误，我们无法处理。',
    'global.error_message.invalid_csrf_token' => '操作无法完成，因为保护器已过期，请重试。',
    'global.error_message.basic' => '我们无法执行此操作。',
    'global.error_message.file_size_limit' => '上传的文件太大，您允许上传的最大文件大小为 %s MB。',
    'global.error_message.password_length' => '密码长度必须在 6 到 64 个字符之间。',
    'global.error_message.passwords_not_matching' => '输入的密码不匹配。',
    'global.error_message.invalid_email' => '输入的电子邮件无效。',
    'global.error_message.invalid_captcha' => '输入的验证码无效。',
    'global.error_message.function_required' => '需要 <code>%s</code>，但您的服务器未启用它。请联系您的服务器管理员。',
    'global.error_message.limit_try_again' => '您已达到限制。请在 %1$s %2$s 后重试。',

    'global.menu.logout' => '退出登录',
    'global.menu.admin' => '管理面板',

    'global.accessibility.toggle_navigation' => '切换导航',
    'global.accessibility.logo_alt' => '网站徽标',
    'global.accessibility.captcha_alt' => '验证码',
    'global.accessibility.captcha_input' => '验证码字段',
    'global.accessibility.whitelisted_file_extensions' => '允许 %s。',
    'global.accessibility.file_size_limit' => '最大 %s MB。',
    'global.accessibility.admin_file_size_limit_help' => '您无法设置高于您实际服务器上传限制的限制。',

    'global.pagination.previous' => '上一页',
    'global.pagination.next' => '下一页',
    'global.pagination.results' => '显示 %3$s 个结果中的第 %1$s-%2$s 个。',

    'global.filters.header' => '筛选',
    'global.filters.reset' => '重置',
    'global.filters.clear' => '清除筛选',
    'global.filters.search' => '搜索',
    'global.filters.search_by' => '搜索依据',
    'global.filters.order_by' => '排序依据',
    'global.filters.order_by_datetime' => '创建日期时间',
    'global.filters.order_by_last_datetime' => '更新日期时间',
    'global.filters.order_type' => '排序类型',
    'global.filters.order_type_asc' => '升序',
    'global.filters.order_type_desc' => '降序',
    'global.filters.results_per_page' => '每页结果数',
    'global.filters.no_data' => '未找到筛选的数据',
    'global.filters.no_data_help' => '未找到符合您筛选条件的结果。',

    'global.date.datetime_readable_format' => '%3$s年%1$s%2$s日',
    'global.date.datetime_small_format' => '%1$s %2$s, %3$s',
    'global.date.datetime_small_readable_format' => '%1$s %2$s',
    'global.date.datetime_ymd_format' => '%1$s-%2$s-%3$s',
    'global.date.datetime_his_format' => '%1$s:%2$s:%3$s',
    'global.date.datetime_ymd_his_format' => '%1$s-%2$s-%3$s %4$s:%5$s:%6$s',
    'global.date.now' => '现在',
    'global.date.cancel' => '取消',
    'global.date.apply' => '应用',
    'global.date.from' => '从',
    'global.date.to' => '到',
    'global.date.custom' => '自定义',
    'global.date.today' => '今天',
    'global.date.yesterday' => '昨天',
    'global.date.last_7_days' => '过去 7 天',
    'global.date.last_30_days' => '过去 30 天',
    'global.date.this_month' => '本月',
    'global.date.last_month' => '上个月',
    'global.date.all_time' => '所有时间',
    'global.date.short_milliseconds' => '毫秒',
    'global.date.short_seconds' => '秒',
    'global.date.second' => '秒',
    'global.date.seconds' => '秒',
    'global.date.minute' => '分钟',
    'global.date.minutes' => '分钟',
    'global.date.hour' => '小时',
    'global.date.hours' => '小时',
    'global.date.day' => '天',
    'global.date.days' => '天',
    'global.date.week' => '周',
    'global.date.weeks' => '周',
    'global.date.month' => '月',
    'global.date.months' => '月',
    'global.date.year' => '年',
    'global.date.years' => '年',
    'global.date.time_ago' => '%1$s %2$s前',
    'global.date.time_until' => '还剩 %1$s %2$s',

    'global.date.long_days.1' => '星期一',
    'global.date.long_days.2' => '星期二',
    'global.date.long_days.3' => '星期三',
    'global.date.long_days.4' => '星期四',
    'global.date.long_days.5' => '星期五',
    'global.date.long_days.6' => '星期六',
    'global.date.long_days.7' => '星期日',

    'global.date.short_days.1' => '周一',
    'global.date.short_days.2' => '周二',
    'global.date.short_days.3' => '周三',
    'global.date.short_days.4' => '周四',
    'global.date.short_days.5' => '周五',
    'global.date.short_days.6' => '周六',
    'global.date.short_days.7' => '周日',

    'global.date.long_months.1' => '一月',
    'global.date.long_months.2' => '二月',
    'global.date.long_months.3' => '三月',
    'global.date.long_months.4' => '四月',
    'global.date.long_months.5' => '五月',
    'global.date.long_months.6' => '六月',
    'global.date.long_months.7' => '七月',
    'global.date.long_months.8' => '八月',
    'global.date.long_months.9' => '九月',
    'global.date.long_months.10' => '十月',
    'global.date.long_months.11' => '十一月',
    'global.date.long_months.12' => '十二月',

    'global.date.short_months.1' => '1月',
    'global.date.short_months.2' => '2月',
    'global.date.short_months.3' => '3月',
    'global.date.short_months.4' => '4月',
    'global.date.short_months.5' => '5月',
    'global.date.short_months.6' => '6月',
    'global.date.short_months.7' => '7月',
    'global.date.short_months.8' => '8月',
    'global.date.short_months.9' => '9月',
    'global.date.short_months.10' => '10月',
    'global.date.short_months.11' => '11月',
    'global.date.short_months.12' => '12月',

    'global.number.decimal_point' => '.',
    'global.number.thousands_separator' => ',',

    'global.emails.copyright' => '版权所有 © %1$s %2$s。',
    'global.emails.anti_phishing_code' => '防钓鱼码：%s',
    'global.emails.is_broadcast' => '您收到此邮件是因为您订阅了我们的新闻通讯。您可以随时%s在此处退订%s。',

    'global.emails.user_welcome.subject' => '欢迎来到 {{WEBSITE_TITLE}}',
    'global.emails.user_welcome.body' => '你好，<strong>{{NAME}}</strong>！<br /><br />欢迎加入我们的网站社区，我们很高兴有你加入！<br /><br />通过访问我们的<a href="{{URL}}">主页</a>或您的<a href="{{DASHBOARD_LINK}}">仪表板</a>开始。<br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_activation.subject' => '确认您的新帐户 - {{WEBSITE_TITLE}}',
    'global.emails.user_activation.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />我们很高兴您加入我们！<br /><br />再一步，您的帐户就准备好了，<br /><br />点击下面的链接加入<strong>{{WEBSITE_TITLE}}</strong><br /><br /><a href="{{ACTIVATION_LINK}}" class="cta">激活帐户</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_pending_email.subject' => '确认您的电子邮件地址更改 - {{WEBSITE_TITLE}}',
    'global.emails.user_pending_email.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />您已请求将您的电子邮件地址从 {{CURRENT_EMAIL}} 更改为 {{NEW_EMAIL}}。<br /><br />请点击下面的链接以确认您的新电子邮件地址。<br /><br /><a href="{{ACTIVATION_LINK}}" class="cta">确认电子邮件地址更改</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_lost_password.subject' => '重置您的密码 - {{WEBSITE_TITLE}}',
    'global.emails.user_lost_password.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />这是您的重置密码链接：<br /><br /><a href="{{LOST_PASSWORD_LINK}}" class="cta">重置密码</a><br /><br />如果您没有请求此操作，可以忽略它。<br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_payment.subject' => '收到付款 - {{WEBSITE_TITLE}}',
    'global.emails.user_payment.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />这是我们收到您付款的确认。<br /><br />您已支付<strong>{{PLAN_NAME}}</strong>计划直到<strong>{{PLAN_EXPIRATION_DATE}}</strong>的费用。<br /><br />您还可以查看您所做的所有<a href="{{USER_PAYMENTS_LINK}}">付款</a>，<a href="{{USER_PLAN_LINK}}">更改您的计划</a>或<a href="{{USER_PLAN_LINK}}">取消它</a>。<br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_plan_expiry_reminder.subject' => '您的计划将在{{DAYS_UNTIL_EXPIRATION}}天内到期 - {{WEBSITE_TITLE}}',
    'global.emails.user_plan_expiry_reminder.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />这是一个简单的提醒，您的<strong>{{PLAN_NAME}}计划</strong>将在<strong>{{DAYS_UNTIL_EXPIRATION}}天</strong>内到期。<br /><br />如果您希望继续使用我们网站的所有功能，您必须续订您的计划。<br /><br /><a href="{{USER_PLAN_RENEW_LINK}}" class="cta">续订计划</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_plan_expired.subject' => '您的计划已过期 - {{WEBSITE_TITLE}}',
    'global.emails.user_plan_expired.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />您的<strong>{{PLAN_NAME}}计划</strong>已过期，因为您没有续订会员资格。<br /><br />如果您希望继续使用我们网站的所有功能，您需要续订会员资格。<br /><br /><a href="{{USER_PLAN_RENEW_LINK}}" class="cta">续订计划</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_deletion_reminder.subject' => '您的帐户将在{{DAYS_UNTIL_DELETION}}天内被删除 - {{WEBSITE_TITLE}}',
    'global.emails.user_deletion_reminder.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />这是一封简单的电子邮件，提醒您，您的帐户将因不活动而在{{DAYS_UNTIL_DELETION}}天内被删除。<br /><br />如果您希望取消此删除，只需使用您的帐户登录，删除过程将停止。<br /><br /><a href="{{LOGIN_LINK}}">登录并停止删除</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.auto_delete_inactive_users.subject' => '您的帐户已被删除 - {{WEBSITE_TITLE}}',
    'global.emails.auto_delete_inactive_users.body' => '你好，<strong>{{NAME}}</strong>，<br /><br />这是一封简单的电子邮件，通知您，由于超过{{INACTIVITY_DAYS}}天不活动，您的帐户已被删除。<br /><br />如果您希望重新获得访问权限，您需要与我们注册另一个帐户。<br /><br /><a href="{{REGISTER_LINK}}" class="cta">重新注册</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.teams_association_create.subject' => '您已被邀请加入“{{TEAM:NAME}}”团队 - {{WEBSITE_TITLE}}',
    'global.emails.teams_association_create.body_login' => '你好，<br /><br />您已被<strong>{{USER:NAME}}</strong> ({{USER:EMAIL}})邀请加入{{WEBSITE_TITLE}}上的<strong>{{TEAM:NAME}}</strong>团队。<br /><br /><a href="{{LOGIN_LINK}}" class="cta">登录并接受邀请</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',
    'global.emails.teams_association_create.body_register' => '你好，<br /><br />您已被<strong>{{USER:NAME}}</strong> ({{USER:EMAIL}})邀请加入{{WEBSITE_TITLE}}上的<strong>{{TEAM:NAME}}</strong>团队。<br /><br /><a href="{{REGISTER_LINK}}" class="cta">注册并接受邀请</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_sessions_events_limit.subject' => '页面浏览量限制已达到 - {{WEBSITE_TITLE}}',
    'global.emails.user_sessions_events_limit.body' => '你好 <strong>{{NAME}}</strong>，<br /><br />这是一份友好的通知，您的<strong>{{WEBSITE_NAME}}</strong>跟踪已停止工作，因为您已达到计划的限制。<br /><br />您的<strong>{{PLAN_NAME}}</strong>计划每月允许<strong>{{SESSIONS_EVENTS_LIMIT}}</strong>次页面浏览。<br /><br />要继续跟踪您的网站，请续订您的计划或升级到更高级别的计划。<br /><br /><a href="{{USER_PLAN_RENEW_LINK}}" class="cta">续订/升级计划</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_events_children_limit.subject' => '访客事件限制已达到 - {{WEBSITE_TITLE}}',
    'global.emails.user_events_children_limit.body' => '你好 <strong>{{NAME}}</strong>，<br /><br />这是一份友好的通知，您的<strong>{{WEBSITE_NAME}}</strong>访客事件跟踪已停止，因为您已达到计划的限制。<br /><br />您的<strong>{{PLAN_NAME}}</strong>计划每月允许<strong>{{EVENTS_CHILDREN_LIMIT}}</strong>次被跟踪的访客事件。<br /><br />要继续跟踪您的网站，请续订您的计划或升级到更高级别的计划。<br /><br /><a href="{{USER_PLAN_RENEW_LINK}}" class="cta">续订/升级计划</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.user_sessions_replays_limit.subject' => '会话重放限制已达到 - {{WEBSITE_TITLE}}',
    'global.emails.user_sessions_replays_limit.body' => '你好 <strong>{{NAME}}</strong>，<br /><br />这是一份友好的通知，您的<strong>{{WEBSITE_NAME}}</strong>会话重放跟踪已停止，因为您已达到计划的限制。<br /><br />您的<strong>{{PLAN_NAME}}</strong>计划每月允许<strong>{{SESSIONS_REPLAYS_LIMIT}}</strong>次会话重放。<br /><br />要继续跟踪您的网站，请续订您的计划或升级到更高级别的计划。<br /><br /><a href="{{USER_PLAN_RENEW_LINK}}" class="cta">续订/升级计划</a><br /><br />此致，<br />{{WEBSITE_TITLE}} 团队。',

    'global.emails.admin_new_user_notification.subject' => '新用户注册 - {{WEBSITE_TITLE}}',
    'global.emails.admin_new_user_notification.body' => '欢迎<strong>{{NAME}}</strong> ({{EMAIL}})来到您的网站！',

    'global.emails.admin_delete_user_notification.subject' => '用户删除了他的帐户 - {{WEBSITE_TITLE}}',
    'global.emails.admin_delete_user_notification.body' => '<strong>{{NAME}}</strong> ({{EMAIL}})的所有数据都已被删除。',

    'global.emails.admin_new_payment_notification.subject' => '通过{{PROCESSOR}}收到新付款，金额为{{TOTAL_AMOUNT}} {{CURRENCY}} - {{WEBSITE_TITLE}}',
    'global.emails.admin_new_payment_notification.body' => '<strong>{{NAME}}</strong> ({{EMAIL}})用户刚刚向您的网站支付了<strong>{{TOTAL_AMOUNT}} {{CURRENCY}}</strong>！<br /><br />祝您财源滚滚！',

    'global.emails.admin_new_affiliate_withdrawal_notification.subject' => '新的联盟提款请求，金额为{{TOTAL_AMOUNT}} {{CURRENCY}} - {{WEBSITE_TITLE}}',
    'global.emails.admin_new_affiliate_withdrawal_notification.body' => '<strong>{{NAME}}</strong> ({{EMAIL}})用户刚刚提交了一份联盟提款请求，金额为<strong>{{TOTAL_AMOUNT}} {{CURRENCY}}</strong>，并附有以下备注：“{{AFFILIATE_WITHDRAWAL_NOTE}}”。<br /><br /><a href="{{ADMIN_AFFILIATE_WITHDRAWAL_LINK}}">查看联盟提款</a>',

    'global.emails.admin_new_domain_notification.subject' => '新的自定义域名待批准 - {{WEBSITE_TITLE}}',
    'global.emails.admin_new_domain_notification.body' => '<strong>{{NAME}}</strong> ({{EMAIL}})用户的自定义域名({{DOMAIN_HOST}})现正等待批准。<br /><br /> <a href="{{ADMIN_DOMAIN_UPDATE_LINK}}">查看域名</a>',

    'global.emails.admin_contact.subject' => '{{SUBJECT}} - {{NAME}} - {{WEBSITE_TITLE}}',
    'global.emails.admin_contact.body' => '<strong>{{NAME}}</strong> - {{EMAIL}}向您发送了以下消息：<br /><br />{{MESSAGE}}',

    'global.notifications.new_user.title' => '新用户！',
    'global.notifications.new_user.description' => '<strong>%1$s</strong> (%2$s)已成功注册。',

    'global.notifications.delete_user.title' => '用户已删除！',
    'global.notifications.delete_user.description' => '<strong>%1$s</strong> (%2$s)已删除其帐户。',

    'global.notifications.new_payment.title' => '新付款！',
    'global.notifications.new_payment.description' => '<strong>%1$s</strong> (%2$s)用户刚刚通过%5$s支付了<strong>%3$s %4$s</strong>。',

    'global.notifications.new_affiliate_withdrawal.title' => '新的联盟提款请求！',
    'global.notifications.new_affiliate_withdrawal.description' => '<strong>%1$s</strong> (%2$s)用户刚刚提交了一份联盟提款请求，金额为<strong>%3$s %4$s</strong>。',

    'global.notifications.new_newsletter_subscriber.title' => '新的新闻通讯订阅者！',
    'global.notifications.new_newsletter_subscriber.description' => '<strong>%1$s</strong> (%2$s)已成功订阅。',

    'global.notifications.user_sessions_events_limit.title' => '已达到每月页面浏览量限制。',
    'global.notifications.user_sessions_events_limit.description' => '要继续跟踪您的网站，请%s续订/升级%s您的计划。',

    'global.notifications.user_events_children_limit.title' => '已达到每月访客事件限制。',
    'global.notifications.user_events_children_limit.description' => '要继续跟踪您的网站，请%s续订/升级%s您的计划。',

    'global.notifications.user_sessions_replays_limit.title' => '已达到每月会话重放限制。',
    'global.notifications.user_sessions_replays_limit.description' => '要继续跟踪您的网站，请%s续订/升级%s您的计划。',

    'global.cookie_consent.menu' => 'Cookies',
    'global.cookie_consent.header' => '我们使用Cookies 🍪',
    'global.cookie_consent.subheader' => '你好，本网站使用必要的cookies以确保其正常运行，并使用跟踪cookies来了解您如何与之互动。后者仅在征得同意后设置。',
    'global.cookie_consent.modal.preferences.header' => 'Cookie偏好设置',
    'global.cookie_consent.modal.header' => 'Cookie使用 📢',
    'global.cookie_consent.modal.subheader' => '我们使用cookies来确保网站的基本功能并增强您的在线体验。您可以随时选择加入/退出每个类别。有关cookies和其他敏感数据的更多详细信息，请阅读完整的<a href="%s" class="cc-link">隐私政策</a>。',
    'global.cookie_consent.modal.necessary.header' => '绝对必要的Cookies',
    'global.cookie_consent.modal.necessary.subheader' => '这些cookies对于我的网站正常运行至关重要。没有这些cookies，网站将无法正常工作。',
    'global.cookie_consent.modal.analytics.header' => '性能和分析Cookies',
    'global.cookie_consent.modal.analytics.subheader' => '这些cookies允许网站记住您过去做出的选择。',
    'global.cookie_consent.modal.targeting.header' => '广告和定向Cookies',
    'global.cookie_consent.modal.targeting.subheader' => '这些cookies收集有关您如何使用网站、访问了哪些页面以及点击了哪些链接的信息。所有数据都是匿名的，不能用于识别您的身份。',
    'global.cookie_consent.accept_all' => '全部接受',
    'global.cookie_consent.reject_all' => '全部拒绝',
    'global.cookie_consent.customize' => '自定义',
    'global.cookie_consent.save' => '保存设置',

    'global.footer.copyright' => '版权所有 &copy; %1$s %2$s。',

    'global.plan_settings.annual_price_savings' => '购买年度计划可节省 %s',
    'global.plan_settings.no_ads' => '无广告',
    'global.plan_settings.no_ads_help' => '与您的帐户和体验相关的一切都没有广告。',
    'global.plan_settings.export' => '%s 导出功能',
    'global.plan_settings.teams_is_enabled' => '团队功能',
    'global.plan_settings.email_reports_is_enabled' => '电子邮件报告',
    'global.plan_settings.email_reports_is_enabled_weekly' => '每周电子邮件报告',
    'global.plan_settings.email_reports_is_enabled_monthly' => '每月电子邮件报告',
    'global.plan_settings.websites_limit' => '%s 个被跟踪的网站',
    'global.plan_settings.sessions_events_limit' => '%s 次页面浏览',
    'global.plan_settings.sessions_events_retention' => '%s 天页面浏览数据保留',
    'global.plan_settings.events_children_limit' => '%s 个访客事件',
    'global.plan_settings.events_children_retention' => '%s 天访客事件数据保留',
    'global.plan_settings.sessions_replays_limit' => '%s 个视频重放',
    'global.plan_settings.sessions_replays_retention' => '%s 天视频重放数据保留',
    'global.plan_settings.websites_heatmaps_limit' => '%s 个热图',
    'global.plan_settings.websites_goals_limit' => '%s 个目标/事件',
    'global.plan_settings.domains_limit' => '%s 个自定义域名',
    'global.plan_settings.api_is_enabled' => 'API访问',
    'global.plan_settings.api_is_enabled_help' => '获得使用REST API的权限。',
    'global.plan_settings.white_labeling_is_enabled' => '白标',
    'global.plan_settings.white_labeling_is_enabled_help' => '白标您的整个帐户标题、徽标、网站图标和页脚。',
    'global.plan_settings.affiliate_commission_percentage' => '%s 联盟百分比',
    'global.plan_settings.affiliate_commission_percentage_help' => '您可以通过联盟计划赚取的百分比金额。',
    'global.plan_settings.per_month' => '每月，每个网站',

    'global.team.is_enabled' => '以团队身份查看',
    'global.team.logout' => '退出团队视图',

    'pwa_install.header' => '安装我们的应用 🪄',
    'pwa_install.or' => '或',
    'pwa_install.subheader.desktop' => '点击地址栏右上角的 <code>%s</code> 图标。',
    'pwa_install.subheader.android_chrome' => '点击 <code>%s</code> 菜单，然后点击 <code>%s 添加到主屏幕</code> 菜单项。',
    'pwa_install.subheader.ios' => '点击 <code>%s</code> 图标，然后点击 <code>%s 添加到主屏幕</code> 菜单项。',
    'pwa_install.subheader.ios_safari' => '点击浏览器的 <code>文件 > 添加到Dock</code> 菜单项。',

    'push_notifications_modal.menu' => '推送通知',
    'push_notifications_modal.header' => '推送通知',
    'push_notifications_modal.subheader' => '如果您想收到我们有用的内容和非垃圾邮件的促销活动，您可以订阅我们的网页推送通知。',
    'push_notifications_modal.subscribe' => '订阅',
    'push_notifications_modal.unsubscribe' => '退订',
    'push_notifications_modal.denied' => '您已拒绝或禁用了推送通知。您必须从浏览器设置中重新启用它们才能订阅。',
    'push_notifications_modal.incompatible' => '您的浏览器窗口与接收推送通知不兼容。',

    'ad_blocker_detector_modal.header' => '检测到广告拦截器',
    'ad_blocker_detector_modal.subheader' => '我们投放广告是为了维持网站的运行。请禁用您的广告拦截器。',
    'ad_blocker_detector_modal.button' => '我已禁用广告拦截器',

    'duplicate_modal.header' => '复制',
    'duplicate_modal.subheader' => '只需点击一下按钮，即可轻松复制此资源。',

    'delete_modal.header' => '删除',
    'delete_modal.subheader1' => '删除 <strong>%s</strong> 的操作无法撤销。',
    'delete_modal.subheader2' => '删除此项的操作无法撤销。',

    'transfer_modal.header' => '转移所有权',
    'transfer_modal.subheader1' => '将 <strong>%s</strong> 转移到另一个用户帐户。',
    'transfer_modal.subheader2' => '将此资源转移到另一个用户帐户。',
    'transfer_modal.success_message' => '%1$s 的所有权已从 %2$s 转移到 %3$s',

    'statistics_reset_modal.header' => '清除统计数据',
    'statistics_reset_modal.subheader' => '清除当前选定的统计数据。此操作无法撤销。',

    'x_reset_modal.header' => '重置',
    'x_reset_modal.subheader' => '重置资源状态并清除其所有关联的日志或统计数据。此操作无法撤销。',

    'bulk_download_modal.header' => '批量下载',
    'bulk_download_modal.subheader' => '您已选择多个条目进行下载，生成ZIP文件可能需要一些时间。',

    'bulk_delete_modal.header' => '批量删除',
    'bulk_delete_modal.subheader' => '您已选择多个条目进行删除，这可能需要一些时间，且此操作无法撤销。',
    'bulk_delete_modal.success_message' => '批量删除过程已成功执行。',

    'analytics.pageviews' => '页面浏览量',
    'analytics.pageview' => '页面浏览',
    'analytics.sessions' => '会话',
    'analytics.visitors' => '访客',
    'analytics.visitor' => '访客',
    'analytics.replays' => '重放',
    'analytics.bounce_rate' => '跳出率',
    'analytics.goals' => '目标',
    'analytics.conversions' => '转化',

    'analytics.pageview.name' => '页面浏览',
    'analytics.pageview.icon' => 'fas fa-fw fa-eye',

    'analytics.custom.name' => '自定义事件',
    'analytics.custom.icon' => 'fas fa-fw fa-bullseye',

    'analytics.landing_page.name' => '着陆页',
    'analytics.landing_page.icon' => 'fas fa-fw fa-plane-arrival',

    'analytics.click.name' => '点击',
    'analytics.click.icon' => 'fas fa-fw fa-mouse-pointer',
    'analytics.click.value' => '在 %s 上',

    'analytics.resize.name' => '调整大小',
    'analytics.resize.icon' => 'fas fa-fw fa-crop',
    'analytics.resize.value' => '到 %s 视口',

    'analytics.scroll.name' => '滚动',
    'analytics.scroll.icon' => 'fas fa-fw fa-arrows-alt-v',
    'analytics.scroll.value' => '从顶部 %s%%',

    'analytics.form.name' => '表单提交',
    'analytics.form.icon' => 'fas fa-fw fa-paper-plane',
    'analytics.referred_by' => '由 %s 推荐',
    'analytics.viewport' => '视口（浏览器尺寸）',

    'analytics.filters.toggle' => '筛选',
    'analytics.filters.header' => '活动筛选',
    'analytics.filters.create' => '添加筛选',

    'analytics.filters.by.continent_code' => '大洲代码',
    'analytics.filters.by.country_code' => '国家代码',
    'analytics.filters.by.city_name' => '城市名称',
    'analytics.filters.by.screen_resolution' => '屏幕分辨率',
    'analytics.filters.by.browser_language' => '浏览器语言',
    'analytics.filters.by.browser_timezone' => '浏览器时区',
    'analytics.filters.by.os_name' => '操作系统',
    'analytics.filters.by.device_type' => '设备',
    'analytics.filters.by.browser_name' => '浏览器',
    'analytics.filters.by.theme' => '主题',
    'analytics.filters.by.path' => '路径',
    'analytics.filters.by.title' => '页面标题',
    'analytics.filters.by.referrer_host' => '来源主机',
    'analytics.filters.by.referrer_path' => '来源路径',
    'analytics.filters.by.utm_source' => 'UTM来源',
    'analytics.filters.by.utm_medium' => 'UTM媒介',
    'analytics.filters.by.utm_campaign' => 'UTM活动',

    'analytics.filters.rule.is' => '是',
    'analytics.filters.rule.is_not' => '不是',
    'analytics.filters.rule.contains' => '包含',
    'analytics.filters.rule.starts_with' => '开头为',
    'analytics.filters.rule.ends_with' => '结尾为',

    'pixel.info_message.dnt' => '“请勿跟踪”已激活。您的隐私受到尊重；不会发生跟踪。',
    'pixel.info_message.optout' => '跟踪退出已确认。您的隐私和决定受到尊重；不会进行跟踪。',

    'domains.breadcrumb' => '自定义域名',
    'domains.title' => '自定义域名',
    'domains.menu' => '自定义域名',
    'domains.header' => '自定义域名',
    'domains.subheader' => '您可以在此处添加自己的自定义域名，以用于您的像素跟踪代码。',
    'domains.create' => '连接域名',
    'domains.domain_id' => '域名',

    'domains.table.host' => '域名',
    'domains.table.is_enabled_pending' => '待定',
    'domains.table.is_enabled_active' => '活跃',

    'domains.help' => '您的域名或子域名必须有一个指向 %1$s 的A记录或指向 %2$s 的CNAME记录。',
    'domains.host' => '域名或子域名',
    'domains.custom_index_url' => '自定义索引URL',
    'domains.custom_index_url_help' => '当访问者登陆域名的索引页时，重定向到特定URL。',
    'domains.custom_not_found_url' => '自定义404未找到URL',
    'domains.custom_not_found_url_help' => '当访问者登陆域名的未找到页面时，重定向到特定URL。',
    'domains.no_data' => '没有添加自定义域名',
    'domains.no_data_help' => '从链接您的第一个自定义域名开始。',
    'domains.error_message.host_exists' => '此自定义域名已存在。',

    'domain_create.breadcrumb' => '连接自定义域名',
    'domain_create.title' => '连接自定义域名',
    'domain_create.menu' => '连接自定义域名',
    'domain_create.header' => '连接自定义域名',
    'domain_create.success_message' => '您的自定义域名已提交以供批准和处理。',

    'domain_update.breadcrumb' => '编辑自定义域名',
    'domain_update.title' => '编辑自定义域名',
    'domain_update.menu' => '编辑自定义域名',
    'domain_update.header' => '编辑自定义域名',
    'domain_update.success_message' => '您的自定义域名更新已提交以供批准和处理。',

    'domain_delete_modal.header' => '删除域名',
    'domain_delete_modal.subheader' => '通过删除域名，与该域名关联的所有网站像素代码将停止工作。此操作无法撤销。',

    'page.breadcrumb' => '页面',
    'page.print' => '打印',
    'page.estimated_reading_time' => '阅读时间 %s',
    'page.total_views' => '浏览量 %s',

    'pages.title' => '页面',
    'pages.header' => '资源中心',
    'pages.subheader' => '您可以在此处根据您的需求找到有用的页面资源。',
    'pages.index.breadcrumb' => '页面',
    'pages.index.popular_pages' => '热门页面',
    'pages.index.pages_categories.header' => '分类',
    'pages.index.pages_categories.total_pages' => '%s 个可用页面',
    'pages.pages_category.breadcrumb' => '页面分类',
    'pages.no_data' => '尚无资源',
    'pages.no_data_help' => '我们的资源部分还有一些工作要做',

    'blog.title' => '博客',
    'blog.title_search' => '搜索 “%s” - 博客',
    'blog.breadcrumb' => '博客',
    'blog.menu' => '博客',
    'blog.header' => '博客',
    'blog.header_search' => '博客 - 搜索 “%s”',
    'blog.subheader' => '通过我们精选的博客文章发现见解。',
    'blog.rss' => 'RSS订阅',
    'blog.categories' => '分类',
    'blog.popular' => '热门文章',
    'blog.total_views' => '浏览量 %s',
    'blog.estimated_reading_time' => '阅读时间 %s',
    'blog.blog_post.title' => '%s - 博客',
    'blog.blog_posts_category.title' => '%s - 分类 - 博客',
    'blog.rating' => '%2$s 个评分中的 %1$s',
    'blog.no_data' => '尚无博客文章',
    'blog.no_data_help' => '我们的博客文章还有一些写作工作要做',

    'help.menu' => '帮助',
    'help.breadcrumb' => '帮助',
    'help.title' => '%s - 帮助',
    'help.pros' => '优点',
    'help.cons' => '缺点',

    'help.introduction.title' => '介绍',
    'help.introduction.menu' => '介绍',
    'help.introduction.header' => '介绍',
    'help.introduction.p1' => '这是 %s 的文档，一个易于使用的网络分析平台，具有跟踪网站的基本功能。',
    'help.introduction.p2' => '这些帮助页面详细说明了一些功能的工作原理以及您如何从中受益。',
    'help.introduction.p3' => '如果您需要更多信息或有任何疑问，请与我们联系。',

    'help.lightweight_tracking.title' => '轻量级跟踪',
    'help.lightweight_tracking.menu' => '轻量级跟踪',
    'help.lightweight_tracking.header' => '轻量级跟踪模式',
    'help.lightweight_tracking.p1' => '我们为那些更关心隐私并希望获得简单高效跟踪解决方案的人开发了轻量级跟踪模式。',
    'help.lightweight_tracking.pro_1' => '极轻量级的跟踪脚本（< 3 kB）',
    'help.lightweight_tracking.pro_2' => '非常快',
    'help.lightweight_tracking.pro_3' => '符合GDPR、CCPA和PECR',
    'help.lightweight_tracking.pro_4' => '无需跟踪同意，因为它不存储任何个人可识别信息',
    'help.lightweight_tracking.pro_5' => '它不使用cookies或本地存储',
    'help.lightweight_tracking.con_1' => '您无法将访客与之前的访问关联起来',
    'help.lightweight_tracking.con_2' => '热图和会话重放不可用',

    'help.advanced_tracking.title' => '高级跟踪',
    'help.advanced_tracking.menu' => '高级跟踪',
    'help.advanced_tracking.header' => '高级跟踪模式',
    'help.advanced_tracking.p1' => '我们为那些想要更深入的分析和访客行为洞察的人开发了高级跟踪模式。',
    'help.advanced_tracking.pro_1' => '深入的访客历史记录',
    'help.advanced_tracking.pro_2' => '热图和会话重放',
    'help.advanced_tracking.pro_3' => '大量的跟踪统计数据',
    'help.advanced_tracking.pro_4' => '访客的自定义参数',
    'help.advanced_tracking.con_1' => '您应该请求跟踪许可',

    'help.goals.title' => '目标',
    'help.goals.menu' => '目标',
    'help.goals.header' => '目标',
    'help.goals.p1' => '目标跟踪现有分析未涵盖的操作，如按钮点击、下载或特定页面浏览（例如结账后的感谢页面）。',

    'help.goals.pageview.header' => '页面浏览',
    'help.goals.pageview.p1' => '页面浏览目标设置简单。当访客到达指定页面时即完成转化。',
    'help.goals.pageview.p2' => '例如，转化后的“感谢”页面（新闻通讯、购买、表单提交）。',

    'help.goals.custom.header' => '自定义',
    'help.goals.custom.p1' => '自定义目标需要额外的代码，在您从仪表板创建新目标时指定。',
    'help.goals.custom.p2' => '使用自定义目标来跟踪页面浏览目标未涵盖的特定事件。',
    'help.goals.custom.p3' => '自定义目标的示例：',
    'help.goals.custom.li1' => '跟踪外部链接的点击',
    'help.goals.custom.li2' => '跟踪高级表单提交',
    'help.goals.custom.li3' => '跟踪特定页面部分的点击',
    'help.goals.custom.li4' => '任何可通过JavaScript跟踪的自定义操作',
    'help.goals.custom.p4' => '用于目标跟踪的JavaScript代码段示例：',
    'help.goals.custom.p5' => '当此代码触发时，将记录目标转化。',
    'help.goals.custom.p6' => '集成到按钮中以触目标事件的代码示例：',

    'help.custom_parameters.title' => '自定义参数',
    'help.custom_parameters.menu' => '自定义参数',
    'help.custom_parameters.header' => '自定义参数',
    'help.custom_parameters.p1' => '要通过自定义参数识别访客，请按照以下步骤操作：',
    'help.custom_parameters.p2' => '这对于有会员系统的网站很有用。当用户登录时，您可以使用我们的跟踪代码指定他们的标识符（例如：电子邮件、用户ID、姓名）。',
    'help.custom_parameters.p3' => '这有助于您了解用户行为并识别他们遇到的任何问题。',
    'help.custom_parameters.p4' => '如示例所示，添加 <code>data-custom-parameters=\'{JSON_PARAMETERS_HERE}\'</code>：',
    'help.custom_parameters.p5' => '如果提供了此参数，您将在“访客”页面上的访客旁边看到<i class="fas fa-fw fa-fingerprint text-primary"></i>图标，表示他们已通过自定义参数被识别。',

    'help.opt_out.title' => '选择退出',
    'help.opt_out.header' => '选择退出',
    'help.opt_out.menu' => '选择退出',
    'help.opt_out.p1' => '我们认真对待隐私，并为我们的跟踪系统提供选择退出选项。',
    'help.opt_out.p2' => '如果您使用我们的跟踪服务，我们建议为用户提供选择退出的选项。',
    'help.opt_out.p3' => '要选择退出，请在使用我们跟踪代码的任何网站的URL中添加以下查询参数：<code>?pixel_optout=true</code>',
    'help.opt_out.p4' => '例如，如果您的网站是<code>https://domain.com/</code>，用户可以通过访问<code>https://domain.com/?pixel_optout=true</code>来选择退出。',
    'help.opt_out.p5' => '这会设置一个本地存储变量以停止跟踪。清除本地存储、更换浏览器或使用隐身模式将重新启用跟踪。',

    'help.dnt.title' => '请勿跟踪',
    'help.dnt.header' => '请勿跟踪',
    'help.dnt.menu' => '请勿跟踪',
    'help.dnt.p1' => '是的，我们尊重支持<a href="https://en.wikipedia.org/wiki/Do_Not_Track">请勿跟踪</a>（DNT）设置的浏览器。',
    'help.dnt.p2' => '“请勿跟踪”是一个浏览器设置，启用后，会告知网站您不希望被跟踪。虽然并非所有浏览器都广泛支持，但如果您的浏览器发送了此设置，我们会尊重它。',
    'help.dnt.p3' => '如果您想跟踪所有人并跳过DNT设置怎么办？作为网站所有者，这也是可以做到的。',
    'help.dnt.p4' => '作为网站所有者，如果您想跟踪所有人并绕过DNT设置，可以这样做。要忽略DNT并跟踪这些访客，请在您的代码中添加<code>data-ignore-dnt="true"</code>，如以下示例所示：',

    'help.faq.menu' => '常见问题',
    'help.faq.header' => '常见问题解答',
    'help.faq.p1' => '一些最常被问到的问题及其快速解答。',
    'help.faq.q1' => '像素跟踪代码会减慢我的网站速度吗？',
    'help.faq.a1' => '不会。它根本不会减慢网站速度，因为JavaScript代码是异步运行的，并且会等到页面准备就绪后才执行并开始跟踪过程。',
    'help.faq.q2' => '为什么有些访客被排除在跟踪之外？',
    'help.faq.a2' => '在某些情况下，访客可能会被排除在跟踪之外：',
    'help.faq.a2li1' => '访客的浏览器禁用了JavaScript',
    'help.faq.a2li2' => '访客的浏览器禁用了localStorage或无法工作',
    'help.faq.a2li3' => '访客的浏览器/浏览器插件正在阻止跟踪',
    'help.faq.a2li4' => '访客已选择退出您网站的跟踪',

    'plan.breadcrumb' => '选择计划',
    'plan.title' => '计划',
    'plan.menu' => '定价',
    'plan.header_new' => '选择您的计划',
    'plan.subheader_new' => '选择一个计划以继续您的订阅。',
    'plan.header_renew' => '续订您的计划',
    'plan.subheader_renew' => '选择一个计划以续订您的订阅。',
    'plan.header_upgrade' => '升级您的计划',
    'plan.subheader_upgrade' => '选择一个计划以升级您的订阅。',

    'plan.custom_plan.monthly' => '每月',
    'plan.custom_plan.quarterly' => '每季度',
    'plan.custom_plan.biannual' => '每半年',
    'plan.custom_plan.annual' => '每年',
    'plan.custom_plan.lifetime' => '终身',

    'plans.choose' => '选择计划',
    'plans.renew' => '续订计划',
    'plans.trial' => '试用 %s 天',
    'plans.contact' => '联系我们',
    'plans.lifetime' => '终身',

    'plan.why.header' => '为什么选择我们？',
    'plan.why.subheader' => '',
    'plan.why.one.header' => '客户服务',
    'plan.why.one.subheader' => '我们的支持团队将帮助您解决有关我们服务的任何问题。',
    'plan.why.two.header' => '隐私',
    'plan.why.two.subheader' => '您控制您在我们网站上帐户内的所有数据。',
    'plan.why.three.header' => '质量',
    'plan.why.three.subheader' => '我们专注于为您提供最佳体验，因为我们完全理解时间是多么宝贵。',

    'plan.faq.header' => '常见问题解答',
    'plan.faq.one.question' => '你们接受哪些付款方式？',
    'plan.faq.one.answer' => '我们接受信用卡、PayPal和加密货币付款。',
    'plan.faq.two.question' => '我可以取消我的订阅吗？',
    'plan.faq.two.answer' => '是的，您当然可以取消订阅，并且在付费日期范围结束之前，您仍然可以访问您已付费的所有功能。',
    'plan.faq.three.question' => '我会收到发票吗？',
    'plan.faq.three.answer' => '是的，在您帐户的任何付款后，系统会自动为您生成发票。',
    'plan.faq.four.question' => '我可以退款吗？',
    'plan.faq.four.answer' => '如果出现问题或您改变主意，我们确实提供退款，如果需要，请联系我们。',

    'pay_billing.breadcrumb' => '账单',
    'pay_billing.title' => '账单',
    'pay_billing.header' => '填写您的账单详情',
    'pay_billing.subheader' => '我们需要您的账单详情以生成正确的发票和处理税务，请仅提供有效的账单详情。',
    'pay_billing.submit' => '更新并继续到 %s 结账',

    'pay.breadcrumb' => '%s 计划',
    'pay.title' => '支付 - %s',
    'pay.attention_title' => '✨结账已准备就绪 🔥',
    'pay.plan_details' => '您将获得什么',
    'pay.accept' => '继续您的订单即表示您确认已阅读、理解并同意本网站的 %1$s 和 %2$s。',

    'pay.free.free_already' => '您已经激活了免费计划。',
    'pay.free.other_plan_not_expired' => '您当前的计划尚未过期，过期后您将获得免费计划。',

    'pay.trial.header' => '开始 %s 计划',
    'pay.trial.subheader' => '您就快成功了，没有任何附加条件。',
    'pay.trial.trial_start' => '开始我的 %s 天试用',
    'pay.trial.trial_skip' => '跳过试用',

    'pay.custom_plan.header' => '购买 %s 计划',
    'pay.custom_plan.subheader' => '您就快成功了，请填写以下表格并结账。',
    'pay.custom_plan.paypal' => 'PayPal',
    'pay.custom_plan.stripe' => 'Stripe',
    'pay.custom_plan.offline_payment' => '线下支付',
    'pay.custom_plan.coinbase' => 'Coinbase',
    'pay.custom_plan.payu' => 'PayU',
    'pay.custom_plan.iyzico' => 'Iyzico',
    'pay.custom_plan.paystack' => 'Paystack',
    'pay.custom_plan.razorpay' => 'Razorpay',
    'pay.custom_plan.mollie' => 'Mollie',
    'pay.custom_plan.yookassa' => 'Yookassa',
    'pay.custom_plan.crypto_com' => 'Crypto.com',
    'pay.custom_plan.paddle' => 'Paddle',
    'pay.custom_plan.mercadopago' => 'MercadoPago',
    'pay.custom_plan.midtrans' => 'Midtrans',
    'pay.custom_plan.flutterwave' => 'Flutterwave',
    'pay.custom_plan.lemonsqueezy' => 'Lemonsqueezy',
    'pay.custom_plan.myfatoorah' => 'Myfatoorah',
    'pay.custom_plan.payment_frequency' => '付款频率',
    'pay.custom_plan.monthly' => '每月付款',
    'pay.custom_plan.quarterly' => '每季度付款',
    'pay.custom_plan.biannual' => '每半年付款',
    'pay.custom_plan.annual' => '每年付款',
    'pay.custom_plan.annual_savings' => '%1$s %2$s',
    'pay.custom_plan.lifetime' => '终身交易',
    'pay.custom_plan.lifetime_help' => '一次性付款',
    'pay.custom_plan.code_button' => '使用折扣码',
    'pay.custom_plan.code' => '代码',
    'pay.custom_plan.payment_processor' => '付款方式',
    'pay.custom_plan.no_processor' => '目前没有可用的付款处理器。',
    'pay.custom_plan.offline_payment_instructions' => '付款说明',
    'pay.custom_plan.offline_payment_proof' => '付款证明',
    'pay.custom_plan.payment_type' => '付款类型',
    'pay.custom_plan.one_time_type' => '一次性付款',
    'pay.custom_plan.recurring_type' => '定期付款',

    'pay.custom_plan.summary.header' => '订单摘要',
    'pay.custom_plan.summary.plan' => '计划',
    'pay.custom_plan.summary.payment_frequency' => '频率',
    'pay.custom_plan.summary.monthly' => '每月',
    'pay.custom_plan.summary.monthly_help' => '每30天',
    'pay.custom_plan.summary.quarterly' => '每季度',
    'pay.custom_plan.summary.quarterly_help' => '每90天',
    'pay.custom_plan.summary.biannual' => '每半年',
    'pay.custom_plan.summary.biannual_help' => '每180天',
    'pay.custom_plan.summary.annual' => '每年',
    'pay.custom_plan.summary.annual_help' => '每365天',
    'pay.custom_plan.summary.lifetime' => '终身',
    'pay.custom_plan.summary.lifetime_help' => '',
    'pay.custom_plan.summary.payment_processor' => '付款方式',
    'pay.custom_plan.summary.payment_type' => '类型',
    'pay.custom_plan.summary.one_time' => '一次性',
    'pay.custom_plan.summary.one_time_help' => '',
    'pay.custom_plan.summary.recurring' => '定期',
    'pay.custom_plan.summary.recurring_help' => '自动计费',
    'pay.custom_plan.summary.plan_price' => '价格',
    'pay.custom_plan.summary.discount' => '折扣',
    'pay.custom_plan.summary.tax_inclusive' => '含税',
    'pay.custom_plan.summary.tax_exclusive' => '不含税',
    'pay.custom_plan.summary.total' => '总计',
    'pay.custom_plan.pay' => '结账',
    'pay.custom_plan.code_redeemable' => '免费兑换 %s 天。',

    'pay.success_message.code' => '已应用代码 %s。',

    'pay.error_message.code_invalid' => '此代码无效。',
    'pay.error_message.code_used' => '您已经使用过此代码。',
    'pay.error_message.canceled_payment' => '您似乎因某种原因取消了付款。',
    'pay.error_message.failed_payment' => '出了点问题，请重试，如果问题仍然存在，请联系网站管理员。',
    'pay.error_message.offline_payment_proof_missing' => '在提交付款订单之前，您必须上传付款证明。',

    'pay_thank_you.title' => '谢谢',
    'pay_thank_you.header' => '谢谢！',
    'pay_thank_you.button' => '前往我的仪表板',
    'pay_thank_you.plan_trial_start' => '您的 %s 天试用期刚刚开始！',
    'pay_thank_you.plan_redeemed' => '您兑换了 %s 天！',
    'pay_thank_you.plan_custom_will_start' => '您的付款已发送，您的新会员资格将被激活！',
    'pay_thank_you.plan_custom_pending' => '您的付款订单已发送，如果证明被接受，您的新会员资格将被激活！',

    'account.title' => '帐户',
    'account.menu' => '帐户',

    'account.plan.header' => '%s 计划',
    'account.plan.subheader' => '于 %s 结束',
    'account.plan.upgrade_plan' => '升级计划',
    'account.plan.renew_plan' => '续订或更改计划',

    'account.settings.header' => '设置',
    'account.settings.subheader' => '您帐户的主要设置。',
    'account.settings.avatar' => '头像',
    'account.settings.timezone' => '时区',
    'account.settings.timezone_help' => '您首选的日期显示方式。',
    'account.settings.anti_phishing_code' => '防钓鱼码',
    'account.settings.anti_phishing_code_help' => '我们发送的每封电子邮件中都会包含此代码，这样您就知道这是我们发送的有效电子邮件。',
    'account.settings.is_newsletter_subscribed' => '已订阅新闻通讯',
    'account.settings.is_newsletter_subscribed_help' => '每月接收几封电子邮件，其中包含我们可能进行的更新和折扣活动。我们不会向您发送垃圾邮件。',
    'account.settings.referral_key' => '推荐密钥',

    'account.billing.header' => '账单详情',
    'account.billing.subheader' => '这些账单详情用于在成功付款后生成发票。',
    'account.billing.subscription_id_active' => '您有一个有效的订阅，在订阅到期或取消之前，您无法更改账单详情。',
    'account.billing.type' => '类型',
    'account.billing.type_personal' => '个人',
    'account.billing.type_business' => '企业',
    'account.billing.name' => '名称',
    'account.billing.address' => '地址',
    'account.billing.county' => '县/区',
    'account.billing.zip' => '邮政编码',
    'account.billing.phone' => '电话',
    'account.billing.tax_id' => '税号',
    'account.billing.notes' => '附加说明',
    'account.billing.notes_help' => '您可以在此处填写您希望在发票上显示的其他数据。',

    'account.change_password.header' => '更改密码',
    'account.change_password.subheader' => '如果您不想更改密码，请不要填写以下任何字段。',
    'account.change_password.current_password' => '当前密码',
    'account.change_password.current_password_help' => '如果您不知道当前密码，您必须注销并使用忘记密码功能重置它。',
    'account.change_password.new_password' => '新密码',
    'account.change_password.repeat_password' => '重复密码',

    'account.twofa.header' => '双因素认证',
    'account.twofa.subheader' => '使用移动认证应用程序获取验证码，每次登录时输入。',
    'account.twofa.is_enabled' => '启用双因素认证',
    'account.twofa.qr' => '1. 扫描二维码',
    'account.twofa.qr_help' => '在您的移动设备上打开您的认证应用程序（例如：Authy、Google Authenticator），并使用您的相机扫描二维码。',
    'account.twofa.secret' => '无法扫描二维码？',
    'account.twofa.secret_help' => '将以下密钥复制到您的应用程序中进行手动设置。',
    'account.twofa.verify' => '2. 输入新生成的令牌',
    'account.twofa.verify_help' => '为确认您已正确设置代码，请输入您移动应用程序中的6位令牌。',

    'account.info_message.user_pending_email' => '已向新的电子邮件地址发送了一封确认邮件。请务必检查并通过电子邮件确认。',
    'account.error_message.invalid_current_password' => '您当前的密码无效。',
    'account.error_message.twofa_check' => '您输入的令牌无效。',
    'account.error_message.referral_key_exists' => '此推荐密钥已在使用中。',
    'account.success_message.account_updated' => '您的帐户已更新。',
    'account.success_message.password_updated' => '您的帐户密码已更新。',

    'account_preferences.title' => '偏好设置',
    'account_preferences.menu' => '偏好设置',
    'account_preferences.header' => '偏好设置',
    'account_preferences.subheader' => '您可以在此处为您的帐户设置与网站使用相关的不同偏好。',
    'account_preferences.success_message' => '您的帐户偏好已更新。',
    'account_preferences.avatar' => '头像',
    'account_preferences.tracking_settings' => '跟踪设置',
    'account_preferences.excluded_ips' => '排除的IP',
    'account_preferences.excluded_ips_help' => '排除IP以防止被跟踪。用逗号分隔的值。',
    'account_preferences.default_settings' => '默认设置',
    'account_preferences.default_results_per_page' => '默认每页结果数',
    'account_preferences.default_order_type' => '默认结果排序',
    'account_preferences.default_order_by_x' => '%s 默认排序依据',
    'account_preferences.white_labeling' => '白标设置',
    'account_preferences.white_label_title' => '白标标题',
    'account_preferences.white_label_logo_light' => '白标浅色徽标',
    'account_preferences.white_label_logo_dark' => '白标深色徽标',
    'account_preferences.white_label_favicon' => '白标网站图标',

    'account_delete.title' => '删除帐户',
    'account_delete.menu' => '删除帐户',
    'account_delete.header' => '删除帐户',
    'account_delete.subheader' => '删除帐户后，您存储的所有数据都将被删除。此操作一旦完成便不可逆转。',
    'account_delete.current_password' => '当前密码',
    'account_delete.error_message.invalid_current_password' => '您当前的密码无效。',
    'account_delete.success_message' => '您的帐户已完全删除。我们很遗憾看到您离开。',

    'account_redeem_code.title' => '兑换代码',
    'account_redeem_code.menu' => '兑换代码',
    'account_redeem_code.header' => '兑换代码',
    'account_redeem_code.subheader' => '如果您拥有特定计划的兑换代码，您可以在这里兑换。',
    'account_redeem_code.plan_id' => '计划',
    'account_redeem_code.code' => '代码',
    'account_redeem_code.success_message' => '您兑换了%2$s计划的%1$s天。',
    'account_redeem_code.success_message_lifetime' => '您兑换了%2$s计划的终身使用权。',
    'account_redeem_code.info_message' => '如果您兑换的代码与您已有的计划不同，您当前的计划将被覆盖。',
    'account_redeem_code.error_message.code_invalid' => '此代码无效。',
    'account_redeem_code.error_message.code_used' => '您已经使用过此代码。',

    'account_plan.title' => '帐户计划',
    'account_plan.menu' => '计划',
    'account_plan.header' => '帐户计划',

    'account_plan.plan.renews' => '计划将于%1$s通过%2$s续订（%3$s %4$s）',
    'account_plan.plan.expires' => '计划于%s结束',
    'account_plan.plan.lifetime' => '计划为终身，不会过期。',

    'account_plan.cancel.header' => '取消订阅',
    'account_plan.cancel.subheader' => '取消订阅后将不再进行任何付款。您仍然可以访问您已付费的功能，直到到期日。',
    'account_plan.cancel.cancel' => '取消订阅',
    'account_plan.cancel.confirm_message' => '您确定要取消订阅吗？',
    'account_plan.cancel.reason' => '从%s取消',

    'account_plan.success_message.subscription_canceled' => '您的定期订阅已取消。',

    'account_payments.title' => '帐户付款',
    'account_payments.menu' => '付款',
    'account_payments.header' => '帐户付款',
    'account_payments.subheader' => '您帐户上进行的所有付款。',

    'account_payments.payment_processor' => '处理器',
    'account_payments.total_amount' => '总金额',
    'account_payments.plan_id' => '计划',
    'account_payments.invoice' => '发票',
    'account_payments.status_pending' => '待批准',
    'account_payments.status_approved' => '已批准',
    'account_payments.no_data' => '未找到付款记录',

    'account_payments.processor' => '处理器',
    'account_payments.type_one_time' => '一次性',
    'account_payments.type_recurring' => '定期',
    'account_payments.frequency' => '频率',
    'account_payments.order_by_total_amount' => '总金额',

    'account_logs.title' => '帐户日志',
    'account_logs.menu' => '日志',
    'account_logs.header' => '帐户日志',
    'account_logs.subheader' => '您最重要的已记录活动列表。',

    'account_logs.logs.no_data' => '您的帐户没有记录的日志',
    'account_logs.logs.no_data_help' => '您将能够在这里找到有关您帐户的重要日志条目。',

    'account_api.title' => '帐户API',
    'account_api.menu' => 'API',
    'account_api.header' => 'API',
    'account_api.subheader' => '请勿与未经授权的人员共享您的API密钥。',
    'account_api.api_key' => 'API密钥',
    'account_api.button' => '重新生成API密钥',
    'account_api.success_message' => '您的API密钥已成功重新生成。',

    'referrals.title' => '推荐',
    'referrals.menu' => '推荐',

    'referrals.invite.header' => '邀请他人',
    'referrals.invite.subheader_once' => '使用以下链接邀请他人加入%s，并从他们对平台的首次付款中获得%s的佣金。',
    'referrals.invite.subheader_forever' => '使用以下链接邀请他人加入%s，并从他们对平台的所有付款中获得%s的佣金。',
    'referrals.invite.referral_key' => '推荐链接',
    'referrals.invite.referral_key_help' => '您可以将%s参数添加到我们网站的任何链接中。',

    'referrals.statistics.header' => '统计数据',
    'referrals.statistics.referrals' => '推荐',
    'referrals.statistics.referrals_help' => '使用您的推荐链接注册的人员。',
    'referrals.statistics.converted_referrals' => '付费推荐',
    'referrals.statistics.converted_referrals_help' => '至少注册并支付过一次计划费用的人员。',
    'referrals.statistics.pending_affiliate_commissions' => '待处理佣金',
    'referrals.statistics.pending_affiliate_commissions_help' => '所有付款在批准前都会被保留30天以进行适当的确认。',
    'referrals.statistics.approved_affiliate_commissions' => '已批准佣金',
    'referrals.statistics.approved_affiliate_commissions_help' => '所有已批准的付款，准备提取。',

    'referrals.withdraw.header' => '提款',
    'referrals.withdraw.subheader' => '一旦您的已批准余额至少达到%s，您就可以创建提款请求。',
    'referrals.withdraw.amount' => '金额',
    'referrals.withdraw.is_paid_paid' => '已支付',
    'referrals.withdraw.is_paid_pending' => '待处理',
    'referrals.withdraw.success_message' => '您的提款请求已发送以供批准和处理。',

    'sso.menu' => '前往 %s',

    'invoice.title' => '发票 %s',
    'invoice.print' => '打印',
    'invoice.invoice' => '发票',
    'invoice.invoice_nr' => '发票号',
    'invoice.invoice_date' => '日期',
    'invoice.vendor' => '供应商',
    'invoice.customer' => '客户',
    'invoice.notes' => '附加说明',
    'invoice.name' => '名称',
    'invoice.address' => '地址',
    'invoice.county' => '县/区',
    'invoice.zip' => '邮政编码',
    'invoice.phone' => '电话',
    'invoice.tax_id' => '税号',

    'invoice.item' => '项目',
    'invoice.amount' => '金额',
    'invoice.plan' => '%s 计划',
    'invoice.frequency' => '%s 访问权限。',
    'invoice.frequency.monthly' => '30天',
    'invoice.frequency.quarterly' => '90天',
    'invoice.frequency.biannual' => '180天',
    'invoice.frequency.annual' => '1年',
    'invoice.frequency.lifetime' => '终身',
    'invoice.code' => '折扣',
    'invoice.code_help' => '使用的代码：%s',
    'invoice.total' => '总计',
    'invoice.paid_via' => '通过 %s 支付',

    'maintenance.title' => '维护模式',
    'maintenance.header' => '维护模式',
    'maintenance.subheader' => '我们正在进行一些维护工作，很快就会回来。',

    'login.menu' => '登录',
    'login.title' => '登录',
    'login.header' => '登录',
    'login.twofa_token' => '双因素令牌',
    'login.remember_me' => '记住我',
    'login.remember_me_help' => '浏览器cookie将用于在此浏览器上记住您%s天。',
    'login.login' => '登录',
    'login.verify' => '验证',
    'login.register' => '没有帐户？%s',
    'login.register_help' => '注册',
    'login.lost_password' => '忘记密码',
    'login.resend_activation' => '重发激活邮件',
    'login.facebook' => '使用Facebook登录',
    'login.google' => '使用Google登录',
    'login.twitter' => '使用X登录',
    'login.discord' => '使用Discord登录',
    'login.linkedin' => '使用LinkedIn登录',
    'login.microsoft' => '使用Microsoft登录',
    'login.info_message.twofa_token' => '需要双因素认证。',
    'login.info_message.logged_in' => '欢迎回来，%s。',
    'login.error_message.twofa_token' => '您的双因素认证令牌无效。',
    'login.error_message.wrong_login_credentials' => '您的登录组合无效。',
    'login.error_message.user_not_active' => '您的帐户未确认或被禁止。',
    'login.error_message.email_is_null' => '您的社交帐户没有关联的电子邮件。',

    'lost_password.title' => '忘记密码',
    'lost_password.header' => '忘记密码',
    'lost_password.subheader' => '我们将向您发送一封带有神奇恢复链接的电子邮件，以重置您的密码。',
    'lost_password.return' => '返回登录',
    'lost_password.submit' => '发送恢复链接',
    'lost_password.success_message' => '我们已向您发送了密码重置链接的电子邮件。',

    'resend_activation.title' => '重发激活邮件',
    'resend_activation.header' => '重发激活邮件',
    'resend_activation.subheader' => '邮件可能会丢失，但我们可以为您的帐户发送另一封激活邮件。',
    'resend_activation.return' => '返回登录',
    'resend_activation.submit' => '发送激活邮件',
    'resend_activation.success_message' => '我们已向您发送了激活链接的电子邮件。',

    'reset_password.title' => '设置新密码',
    'reset_password.header' => '设置新密码',
    'reset_password.subheader' => '为提高安全性，请确保您的新密码足够强大。',
    'reset_password.return' => '返回登录',
    'reset_password.new_password' => '新密码',
    'reset_password.repeat_password' => '重复您的新密码',
    'reset_password.submit' => '设置密码',
    'reset_password.success_message' => '您的新密码已设置。',

    'activate_user.user_activation' => '您的帐户已确认并现已激活。',
    'activate_user.user_pending_email' => '您的新电子邮件地址已确认。',

    'register.title' => '注册',
    'register.menu' => '注册',
    'register.header' => '注册',
    'register.repeat_password' => '重复密码',
    'register.accept' => '我确认我已阅读并理解网站的%1$s和%2$s。',
    'register.is_newsletter_subscribed' => '我同意每月接收几封来自新闻通讯的电子邮件。您可以随时退订。',
    'register.register' => '注册',
    'register.login' => '已有帐户？%s',
    'register.login_help' => '登录',
    'register.error_message.name_length' => '名称长度必须在1到64个字符之间。',
    'register.error_message.email_exists' => '此电子邮件地址已在使用中。',
    'register.error_message.blacklisted_domain' => '此电子邮件域已被列入黑名单。',
    'register.error_message.blacklisted_country' => '您的国家已被列入黑名单。',
    'register.success_message.registration' => '我们已向您发送了激活链接的电子邮件。',
    'register.success_message.login' => '欢迎来到我们的平台，我们很高兴有您在这里。',

    'dashboard.breadcrumb' => '仪表板',
    'dashboard.title' => '仪表板 - %s',
    'dashboard.title_dynamic' => '%1$s - %2$s',
    'dashboard.menu' => '仪表板',

    'dashboard.basic.no_data' => '无可用数据',
    'dashboard.basic.no_data_help' => '请确保您已正确安装跟踪代码。',

    'dashboard.basic.chart.pageviews' => '页面浏览量',
    'dashboard.basic.chart.sessions' => '会话',
    'dashboard.basic.chart.visitors' => '访客',

    'dashboard.all_pages' => '所有页面',
    'dashboard.locations' => '位置',
    'dashboard.devices' => '设备',
    'dashboard.sources' => '来源',

    'dashboard.continents.header' => '大洲',
    'dashboard.countries.header' => '国家',
    'dashboard.cities.header' => '城市',

    'dashboard.paths.header' => '页面',
    'dashboard.paths.path' => '页面',

    'dashboard.landing_paths.header' => '着陆页',
    'dashboard.landing_paths.path' => '页面',

    'dashboard.exit_paths.header' => '退出页',
    'dashboard.exit_paths.path' => '页面',

    'dashboard.referrers.header' => '来源',
    'dashboard.referrers.referrer_host' => '域名',
    'dashboard.referrers.null' => '直接访问',

    'dashboard.referrer_paths.header' => '来源路径',
    'dashboard.referrer_paths.referrer_path' => '路径',
    'dashboard.referrer_paths.null' => '主页',

    'dashboard.social_media_referrers.header' => '社交媒体',
    'dashboard.social_media_referrers.referrer_host' => '网站',

    'dashboard.search_engines_referrers.header' => '搜索引擎',
    'dashboard.search_engines_referrers.referrer_host' => '搜索引擎',

    'dashboard.utms.header' => 'UTM',
    'dashboard.utms.utm' => 'UTM',
    'dashboard.utms.utm_source' => '来源',
    'dashboard.utms.utm_medium' => '媒介',
    'dashboard.utms.utm_campaign' => '活动',

    'dashboard.themes.header' => '主题',
    'dashboard.themes.theme' => '主题',
    'dashboard.themes.dark' => '🌙 深色',
    'dashboard.themes.light' => '☀️ 浅色',

    'dashboard.screen_resolutions.header' => '分辨率',
    'dashboard.screen_resolutions.resolution' => '分辨率',

    'dashboard.browser_languages.header' => '语言',
    'dashboard.browser_languages.language' => '语言',

    'dashboard.browser_timezones.header' => '时区',
    'dashboard.browser_timezones.timezone' => '时区',

    'dashboard.operating_systems.header' => '操作系统',
    'dashboard.operating_systems.os_name' => '操作系统',

    'dashboard.device_types.header' => '设备',
    'dashboard.device_types.device_type' => '设备类型',

    'dashboard.browser_names.header' => '浏览器',
    'dashboard.browser_names.browser' => '浏览器',

    'dashboard.goals.header' => '目标',
    'dashboard.goals.goal' => '目标',

    'goals.breadcrumb' => '目标',
    'goals.title' => '目标',
    'goals.header' => '目标',
    'goals.subheader' => '跟踪访客的特定事件，如按钮点击、表单提交甚至页面访问。',

    'realtime.breadcrumb' => '实时分析',
    'realtime.title' => '实时分析',
    'realtime.title_dynamic' => '%s 📊',
    'realtime.menu' => '实时',
    'realtime.header' => '实时分析',
    'realtime.subheader' => '数据基于最近5分钟的活动，并每10秒刷新一次。',
    'realtime.visitors' => '活跃用户',
    'realtime.pageviews' => '最近的页面浏览量',

    'pageviews.breadcrumb' => '页面浏览量',
    'pageviews.title' => '页面浏览量',
    'pageviews.menu' => '页面浏览量',
    'pageviews.header' => '页面浏览量',
    'pageviews.subheader' => '我们在此网站上跟踪的所有访客事件。',
    'pageviews.expiration_date' => '到期日期',

    'statistics.breadcrumb' => '统计数据',
    'statistics.title' => '统计数据 - %s',
    'statistics.title_dynamic' => '%1$s - %2$s',
    'statistics.password.title' => '密码保护的统计数据',
    'statistics.password.header' => '密码保护的统计数据',
    'statistics.password.subheader' => '您必须输入正确的密码才能查看此网站的统计数据。您的密码将被记住30天。',
    'statistics.password.error_message' => '密码不正确。',

    'referrer_paths_modal.header' => '来源路径',
    'utms_medium_campaign_modal.header' => 'UTM',

    'goal_update_modal.header' => '编辑目标',

    'goal_create_modal.header' => '创建一个目标',
    'goal_create_modal.subheader' => '跟踪转化或特定操作，如按钮点击或表单提交。',
    'goal_create_modal.type' => '目标触发器',
    'goal_create_modal.type_pageview' => '页面浏览',
    'goal_create_modal.type_custom' => '自定义事件',
    'goal_create_modal.path' => '页面路径',
    'goal_create_modal.path_placeholder' => 'thank-you',
    'goal_create_modal.key' => '键',
    'goal_create_modal.key_placeholder' => 'custom-identifier',
    'goal_create_modal.code' => 'Javascript代码',
    'goal_create_modal.code_help' => '此JavaScript代码段允许您在Web应用程序中激活自定义事件。',

    'visitors.title' => '访客',
    'visitors.menu' => '访客',
    'visitors.breadcrumb' => '访客',
    'visitors.header' => '访客',
    'visitors.average_time_per_session' => '平均会话时长',
    'visitors.average_sessions_per_visitor' => '平均每访客会话数',
    'visitors.system' => '系统',
    'visitors.last_date' => '最后活跃',
    'visitors.total_sessions' => '%s 会话',
    'visitors.custom_parameters' => '%s 自定义参数',
    'visitors.since' => '自',

    'visitor.title' => '访客',
    'visitor.breadcrumb' => '访客',
    'visitor.custom_parameters' => '自定义参数',
    'visitor.total_goals_conversions' => '总转化数',
    'visitor.goals_conversions' => '目标转化',
    'visitor.total_sessions' => '总会话数',
    'visitor.date' => '首次会话',
    'visitor.last_date' => '最后活跃',
    'visitor.device_type' => '设备',
    'visitor.operating_system' => '操作系统',
    'visitor.browser' => '浏览器',
    'visitor.browser_language' => '浏览器语言',
    'visitor.browser_timezone' => '浏览器时区',
    'visitor.screen_resolution' => '屏幕分辨率',
    'visitor.average_time_per_session' => '平均会话时长',
    'visitor.pageviews' => '%s 页面浏览量',
    'visitor.replays' => '查看重放',
    'visitor.ip_private' => '访客',
    'visitor.unknown_duration' => '未知时长',
    'visitor.duration_tooltip' => '会话时长为近似值，从第一次到最后一次页面加载测量',
    'visitor.no_data' => '这些日期没有可用数据',

    'session_events_modal.header' => '会话事件',

    'heatmaps.title' => '热图',
    'heatmaps.menu' => '热图',
    'heatmaps.header' => '热图',
    'heatmaps.breadcrumb' => '热图',
    'heatmaps.no_data' => '没有创建的热图。',
    'heatmaps.no_data_help' => '点击右上角的按钮添加一个。',
    'heatmaps.create' => '创建热图',
    'heatmaps.retake_snapshots' => '重新拍摄快照',
    'heatmaps.heatmap' => '热图',
    'heatmaps.is_enabled_true' => '正在收集数据',
    'heatmaps.is_enabled_false' => '已暂停',
    'heatmaps.snapshot_id_desktop' => '桌面快照已拍摄',
    'heatmaps.snapshot_id_desktop_null' => '未拍摄桌面快照',
    'heatmaps.snapshot_id_tablet' => '平板快照已拍摄',
    'heatmaps.snapshot_id_tablet_null' => '未拍摄平板快照',
    'heatmaps.snapshot_id_mobile' => '移动快照已拍摄',
    'heatmaps.snapshot_id_mobile_null' => '未拍摄移动快照',

    'heatmap.title' => '热图',
    'heatmap.menu' => '热图',
    'heatmap.header' => '热图',
    'heatmap.breadcrumb' => '热图',
    'heatmap.click' => '%s 次点击',
    'heatmap.x_size' => '%s 尺寸',
    'heatmap.no_data' => '我们仍在等待数据',
    'heatmap.no_data_help' => '第一个打开热图页面的访客将创建初始快照。',
    'heatmap.error_message.js' => '我们在重放会话或其中某些部分时检测到一些问题。',

    'heatmap_create_modal.header' => '创建一个新的热图',
    'heatmap_create_modal.subheader' => '跟踪多个人在同一页面上的流程。',
    'heatmap_create_modal.path' => '热图路径',
    'heatmap_create_modal.path_placeholder' => 'page-inside-your-website',
    'heatmap_create_modal.path_help' => '指定您要为其创建此热图的网站的确切路径。',

    'heatmap_update_modal.header' => '编辑热图',
    'heatmap_update_modal.subheader' => '编辑一个已有的热图。',
    'heatmap_update_modal.is_enabled' => '热图状态',
    'heatmap_update_modal.is_enabled_help' => '启用或禁用此热图上的数据收集。',

    'heatmap_retake_snapshots_modal.header' => '重新拍摄快照',
    'heatmap_retake_snapshots_modal.subheader' => '清除热图页面的当前快照并允许其重新生成。',
    'heatmap_retake_snapshots_modal.snapshot_id_desktop' => '桌面快照',
    'heatmap_retake_snapshots_modal.snapshot_id_tablet' => '平板快照',
    'heatmap_retake_snapshots_modal.snapshot_id_mobile' => '移动快照',
    'heatmap_retake_snapshots_modal.success_message' => '选定的快照已被清除！',

    'replays.title' => '重放',
    'replays.menu' => '重放',
    'replays.delete' => '删除重放',
    'replays.header' => '重放',
    'replays.breadcrumb' => '重放',
    'replays.average_events_per_replay' => '平均每个重放的事件数',
    'replays.average_duration_per_replay' => '平均每个重放的时长',

    'replays.replay' => '重放',
    'replays.replay.visitor' => '访客',
    'replays.replay.session' => '会话',
    'replays.replay.date' => '时间',
    'replays.replay.first_date' => '开始于 %s',
    'replays.replay.last_date' => '结束于 %s',
    'replays.replay.expiration_date' => '过期于 %s',
    'replays.replay.events' => '%s 个事件',
    'replays.replay.since' => '自',
    'replays.replay.sessions_replays' => '重放会话',

    'replay.title' => '重放',
    'replay.menu' => '重放',
    'replay.header' => '重放',
    'replay.breadcrumb' => '重放',
    'replay.events' => '跟踪的事件',
    'replay.size' => '大小',
    'replay.duration' => '重放时长',
    'replay.time_range' => '时间起止',
    'replay.expiration_date' => '重放到期',
    'replay.is_offloaded' => '已卸载',
    'replay.error_message' => '抱歉，我们在此重放会话中检测到一些问题，无法显示。',
    'replay_events_modal.header' => '重放页面事件',
    'replay_events_modal.help' => '此模式中仅显示页面浏览类型的事件。',

    'websites.title' => '网站',
    'websites.menu' => '网站',
    'websites.header' => '网站',
    'websites.subheader' => '查看和管理您所有已添加的网站。',
    'websites.create' => '添加网站',

    'websites.website' => '网站',
    'websites.this_month' => '本月',
    'websites.usage' => '使用情况',
    'websites.sessions_events' => '页面浏览量',
    'websites.events_children' => '访客事件',
    'websites.sessions_replays' => '重放',
    'websites.websites_heatmaps' => '热图',
    'websites.websites_goals' => '目标',
    'websites.email_reports' => '电子邮件报告',
    'websites.pixel_key' => '跟踪代码',
    'websites.tracking_type' => '跟踪类型',
    'websites.tracking_type_normal' => '高级跟踪',
    'websites.tracking_type_normal_help' => '这种类型的跟踪将使用本地存储和每个访客的随机唯一标识符，以了解用户何时返回并将访问和其他数据与该特定访客关联。',
    'websites.tracking_type_lightweight' => '轻量级跟踪',
    'websites.tracking_type_lightweight_help' => '这种类型的跟踪将不使用任何cookies、本地存储或任何访客标识符，完全符合GDPR、CCPA和PECR的开箱即用要求。这种跟踪无需征得同意。',
    'websites.tracking_type_help' => '跟踪类型以后无法更改。',
    'websites.ip_storage_is_enabled' => 'IP跟踪',
    'websites.ip_storage_is_enabled_help' => '我们建议仅在获得用户同意存储其IP后才启用此功能。',
    'websites.domain_id' => '自定义域名',
    'websites.domain_id_help' => '为您的跟踪代码URL使用自定义域名。有助于绕过广告拦截器。',
    'websites.host' => '网站',
    'websites.host_help' => '跟踪仅在您指定的<strong>domain.com</strong>、<strong>sub.domain.com</strong>或<strong>domain.com/path</strong>上有效。',
    'websites.events_children_is_enabled' => '跟踪访客事件',
    'websites.events_children_is_enabled_help' => '启用或禁用对鼠标点击、表单提交、调整大小或滚动的跟踪。',
    'websites.sessions_replays_is_enabled' => '会话重放',
    'websites.sessions_replays_is_enabled_help' => '启用或禁用视觉会话重放跟踪。这是一种比普通选项更高级的跟踪类型。',
    'websites.email_reports_is_enabled_help' => '通过电子邮件接收关于您网站的简单易懂的分析报告。',
    'websites.is_enabled' => '跟踪',
    'websites.is_enabled_help' => '完全启用或禁用网站的跟踪。',
    'websites.bot_exclusion_is_enabled' => '机器人排除',
    'websites.bot_exclusion_is_enabled_help' => '排除广为人知的机器人被跟踪（例如：Google Bot, Yahoo Bot ...等）。',
    'websites.query_parameters_tracking_is_enabled' => '跟踪查询参数',
    'websites.query_parameters_tracking_is_enabled_help' => '启用此功能将允许跟踪查询参数而不是忽略它们。',
    'websites.public_statistics_is_enabled' => '公共统计数据',
    'websites.public_statistics_is_enabled_help' => '启用此功能将允许您通过链接共享您的总体统计数据。',
    'websites.public_statistics_password' => '公共统计密码',
    'websites.public_statistics_password_help' => '为您的公共统计页面设置密码。留空以禁用。',
    'websites.excluded_ips' => '排除的IP',
    'websites.excluded_ips_help' => '排除IP以防止被跟踪。用逗号分隔的值。',
    'websites.error_message.blacklisted_domain' => '此域名已被列入黑名单。',
    'websites.no_data' => '现在添加您的第一个网站',
    'websites.no_data_help' => '点击右上角的按钮添加一个。',

    'website_create_modal.header' => '添加一个新网站',
    'website_create_modal.subheader' => '轻松添加一个您想要跟踪的新网站。',

    'website_update_modal.header' => '编辑网站',

    'website_pixel_key_modal.header' => '安装像素',
    'website_pixel_key_modal.subheader' => '复制并粘贴以下JS代码片段到您网站的<code>head</code>标签结束之前。',
    'website_pixel_key_modal.copy' => '复制像素',
    'website_pixel_key_modal.copied' => '已复制！',

    'website_public_statistics_modal.header' => '公共统计数据',
    'website_public_statistics_modal.subheader' => '您网站统计数据的可共享链接。',
    'website_public_statistics_modal.copy' => '复制URL',
    'website_public_statistics_modal.copied' => '已复制！',

    'website_delete_modal.header' => '删除网站',
    'website_delete_modal.subheader' => '与该网站相关的所有数据将被完全删除。此操作无法撤销。',

    'teams.title' => '团队',
    'teams.menu' => '团队',
    'teams.breadcrumb' => '团队',
    'teams.header' => '团队',
    'teams.subheader' => '创建、邀请或被邀请加入他人的团队。',

    'teams.teams.header' => '我的团队',
    'teams.teams.create' => '创建团队',
    'teams.teams.team' => '团队',
    'teams.teams.websites_ids' => '网站',
    'teams.teams.users' => '成员',
    'teams.teams.no_data' => '添加您的第一个团队并邀请他人',
    'teams.teams.no_data_help' => '点击右上角的按钮添加一个。',

    'teams.teams_associations.header' => '您所属的团队',
    'teams.teams_associations.team' => '团队',
    'teams.teams_associations.websites_ids' => '网站',
    'teams.teams_associations.is_accepted' => '状态',
    'teams.teams_associations.is_accepted_invited' => '已邀请',
    'teams.teams_associations.accepted_date' => '已加入',
    'teams.teams_associations.accept' => '接受',
    'teams.teams_associations.decline' => '拒绝',
    'teams.teams_associations.login' => '登录',
    'teams.teams_associations.delete' => '离开团队',
    'teams.teams_associations.no_data' => '您不属于任何团队',
    'teams.teams_associations.no_data_help' => '',

    'team_create_modal.header' => '创建一个新团队',
    'team_create_modal.subheader' => '与您的成员共享访问权限。',
    'team_create_modal.websites_ids' => '访问网站',
    'team_create_modal.websites_ids_help' => '您希望共享访问权限的网站。',

    'team_update_modal.header' => '编辑团队',
    'team_update_modal.subheader' => '更改一个已有的团队的设置。',

    'team_delete_modal.header' => '删除团队',
    'team_delete_modal.subheader' => '所有团队成员将失去对您所选网站的访问权限。此操作无法撤销。',

    'team.title' => '团队 - %s',
    'team.menu' => '团队',
    'team.breadcrumb' => '团队',
    'team.header' => '%s 团队',

    'team.teams_associations.header' => '成员',
    'team.teams_associations.create' => '添加成员',
    'team.teams_associations.user' => '用户',
    'team.teams_associations.date' => '已邀请',
    'team.teams_associations.is_accepted' => '状态',
    'team.teams_associations.is_accepted_invited' => '已邀请',
    'team.teams_associations.accepted_date' => '已加入',
    'team.teams_associations.no_data' => '添加您的第一个团队成员',
    'team.teams_associations.no_data_help' => '点击右上角的按钮邀请。',

    'team_association_delete_modal.header' => '移除用户访问权限',
    'team_association_delete_modal.subheader' => '移除用户对此团队的所有访问权限。此操作无法撤销。',
    'team_association_delete_modal.header2' => '移除您的访问权限',
    'team_association_delete_modal.subheader2' => '从此团队中移除您的会员资格。此操作无法撤销。',
    'team_association_delete_modal.success_message' => '团队关联删除已成功执行。',

    'team_association_create_modal.header' => '添加新成员',
    'team_association_create_modal.subheader' => '与您的成员共享访问权限。',
    'team_association_create_modal.success_message' => '已向该电子邮件发送邀请。',
    'team_association_create_modal.error_message.email_exists' => '此电子邮件已与此团队关联。',

    'index.title' => '用户会话分析',
    'index.meta_description' => '',
    'index.meta_keywords' => '',
    'index.header' => '一体化网络分析。',
    'index.subheader' => '简单友好的分析。跟踪您的用户旅程，重放会话，收集热图等等。',
    'index.subheader2' => '符合GDPR、CCPA和PECR',
    'index.get_started' => '开始使用',
    'index.breadcrumb' => '主页',
    'index.menu' => '主页',
    'index.stats' => '我们跟踪了<span class=\'text-primary-400\'>%1$s个网站</span>并存储了超过<span class=\'text-primary-400\'>%2$s次页面浏览</span>。',
    'index.example' => '统计演示',
    'index.example_help' => '高级跟踪数据不会显示在公共统计页面中。',
    'index.hero_image_alt' => '应用仪表板的屏幕截图',
    'index.visitors_image_alt' => '应用访客列表页面的屏幕截图',
    'index.behaviour_image_alt' => '应用访客事件列表页面的屏幕截图',
    'index.realtime_image_alt' => '应用实时分析页面的屏幕截图',
    'index.heatmaps_image_alt' => '应用热图页面的屏幕截图',
    'index.replays_image_alt' => '应用会话重放页面的屏幕截图',
    'index.teams_image_alt' => '应用团队页面的屏幕截图',
    'index.goals_image_alt' => '应用目标分析页面的屏幕截图',
    'index.export_image_alt' => '应用仪表板分析页面的屏幕截图',
    'index.email_reports_image_alt' => '应用电子邮件报告分析的屏幕截图',
    'index.domains_image_alt' => '应用自定义域名页面的屏幕截图',
    'index.custom_parameters_image_alt' => '应用访客自定义参数示例的屏幕截图',

    'index.setup.header' => '在<span class="text-primary">任何网站</span>上轻松设置和集成。',
    'index.setup.subheader' => '将<span class="font-weight-bold">一行代码</span>复制并粘贴到您的网站中。',

    'index.steps.one' => '跟踪模式',
    'index.steps.one_text' => '轻量级和高级匿名行为跟踪。',
    'index.steps.two' => '我们尊重您的数据',
    'index.steps.two_text' => '永远是您的。随时可删除。',
    'index.steps.three' => '私密、安全且合规',
    'index.steps.three_text' => '我们尊重所有现代隐私和跟踪法规。',

    'index.domains.header' => '自定义域名',
    'index.domains.subheader' => '连接您自己的域名以获取自定义像素JS代码链接。',

    'index.custom_parameters.header' => '自定义参数',
    'index.custom_parameters.subheader' => '将您网站的变量动态链接到被跟踪的访客。',

    'index.email_reports.header' => '电子邮件报告',
    'index.email_reports.subheader' => '定期获取您网站总体统计数据的电子邮件简报。',

    'index.teams.header' => '团队',
    'index.teams.subheader' => '邀请他人并与您的团队共享对您分析的访问权限。',

    'index.goals.header' => '目标跟踪',
    'index.goals.subheader' => '创建自定义分析目标以轻松跟踪转化。',

    'index.export.header' => '数据导出',
    'index.export.subheader' => '只需点击一下按钮，即可将您的数据导出为CSV、JSON或PDF。',

    'index.visitors.name' => '访客',
    'index.visitors.header' => '访客历史',
    'index.visitors.subheader' => '完全匿名的访客历史。了解您的访客何时返回以及他们在做什么。',

    'index.visitor_behaviour.name' => '访客行为',
    'index.visitor_behaviour.header' => '了解您的用户',
    'index.visitor_behaviour.subheader' => '在不侵犯隐私的情况下检查每个访客在您网站上的旅程。',

    'index.realtime_data.name' => '实时信息',
    'index.realtime_data.header' => '实时访客分析',
    'index.realtime_data.subheader' => '获取关于您用户在您网站上行为的实时数据。',
    'index.realtime_data.countries' => '当前活跃国家',
    'index.realtime_data.devices' => '使用的设备',
    'index.realtime_data.pages' => '访问的页面',

    'index.session_recording.name' => '会话录制',
    'index.session_recording.header' => '录制和重放访客会话',
    'index.session_recording.subheader' => '观看用户在您网站上所做操作的完整视频演示。',
    'index.session_recording.privacy' => '自动隐藏私人信息',
    'index.session_recording.mouse' => '鼠标点击和轨迹',
    'index.session_recording.pages' => '完整的页面旅程',

    'index.heatmaps.name' => '热图',
    'index.heatmaps.header' => '隐私友好的热图',
    'index.heatmaps.subheader' => '收集匿名点击数据并生成易于理解的热图。',
    'index.heatmaps.clicks' => '每个设备的总点击次数',
    'index.heatmaps.devices' => '桌面、平板、移动版热图',
    'index.heatmaps.dynamic' => '全页热图',

    'index.testimonials.header' => '听听大家怎么说',
    'index.testimonials.one.text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare ex. Vivamus eu ex non orci condimentum placerat ac ac nisi. Nam velit libero, hendrerit vitae auctor eget, congue ut ante.',
    'index.testimonials.one.name' => 'Andrea',
    'index.testimonials.one.attribute' => 'Writer Magazine',
    'index.testimonials.two.text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent finibus vestibulum porta. Sed id eros quam. Nunc at nisi vel arcu placerat gravida.',
    'index.testimonials.two.name' => 'George',
    'index.testimonials.two.attribute' => 'Lorem Ipsum Founder',
    'index.testimonials.three.text' => 'Praesent finibus vestibulum porta. Sed id eros quam. Proin lacinia ipsum porttitor, sollicitudin est in, ornare ex. Vivamus eu ex non orci condimentum placerat ac ac nisi. Nam velit libero, hendrerit vitae auctor eget, congue ut ante.',
    'index.testimonials.three.name' => 'Calvin',
    'index.testimonials.three.attribute' => 'SAAS Lorem Owner',

    'index.faq.header' => '%1$s您常见%2$s问题的%1$s答案%2$s',
    'index.faq.one.question' => '如何编辑这个？',
    'index.faq.one.answer' => '所有FAQ部分都可以从管理面板的语言部分进行编辑。',
    'index.faq.two.question' => 'Lorem ipsum dolor sit amet',
    'index.faq.two.answer' => 'Lorem ipsum dolor sit amet, vim eu quem nonumes omittam. Mutat facete patrioque et est, nusquam abhorreant definiebas te sit, albucius urbanitas pro ad. Ne nemore officiis sed. Cu mundi docendi qui, nam nonumes maluisset constituto an, vix ea solum accusamus consequuntur.',
    'index.faq.three.question' => 'Virtute feugiat ocurreret ad cum',
    'index.faq.three.answer' => 'Virtute feugiat ocurreret ad cum, pro in posse ullum adversarium, te qui stet graece antiopam. Amet omnesque indoctum ut mel, ea eam sonet saperet nostrum. Te modus delectus mel, pri populo definitionem ne, an eam hinc labitur inciderint. Novum vivendum gloriatur ex nec, ad vocibus eleifend deterruisset pro, mutat voluptaria repudiandae eum ea. Ipsum soluta cotidieque sea ut, aliquando scripserit no has, iisque impetus erroribus pro ad. Case labitur scaevola vis ut, clita meliore te eos.',
    'index.faq.four.question' => 'Mel iusto putant feugiat et',
    'index.faq.four.answer' => 'Mel iusto putant feugiat et, qui alii virtute eu. Diceret corrumpit mei an. Ius ei congue iudico, ex quo delectus indoctum. Mnesarchum reprehendunt pro ex, ea vix amet maluisset, in autem omnes consectetuer eum.',

    'index.pricing.header' => '简单、透明的定价。',
    'index.pricing.subheader' => '选择适合您和您预算的计划。',

    'index.cta.header' => '拥有您的分析数据。',
    'index.cta.subheader' => '简单易懂的分析，但功能强大。',
    'index.cta.pricing' => '定价',
    'index.cta.register' => '注册',

    'index.blog.header' => '最新%1$s博客%2$s文章',

    'api.error_message.no_bearer' => '请求缺少Bearer身份验证头。',
    'api.error_message.no_access' => '您没有API的访问权限。',
    'api.error_message.rate_limit' => '您已达到一分钟内的请求限制，请稍候。',
    'api.error_message.not_found' => '您正在寻找的资源不存在。',

    'api_documentation.menu' => 'API文档',
    'api_documentation.breadcrumb' => 'API文档',
    'api_documentation.title' => 'API文档',
    'api_documentation.title_dynamic' => '%s - API文档',
    'api_documentation.header' => 'API文档',
    'api_documentation.subheader' => '这是可用API端点的文档，它们是围绕<strong>REST架构</strong>构建的。所有API端点都将返回一个<strong>JSON响应</strong>，并带有标准的<strong>HTTP响应代码</strong>，并且需要通过<strong>API密钥进行Bearer身份验证</strong>。',
    'api_documentation.endpoint' => '端点',
    'api_documentation.example' => '示例',
    'api_documentation.response' => '响应示例',
    'api_documentation.api_key' => 'API密钥',
    'api_documentation.base_url' => '基础URL',
    'api_documentation.parameters' => '参数',
    'api_documentation.required' => '必填',
    'api_documentation.optional' => '可选',
    'api_documentation.string' => '字符串',
    'api_documentation.int' => '整数',
    'api_documentation.float' => '浮点数',
    'api_documentation.boolean' => '布尔值',
    'api_documentation.file' => '文件',
    'api_documentation.array' => '数组',
    'api_documentation.read_all' => '检索所有',
    'api_documentation.read' => '检索一个',
    'api_documentation.create' => '创建',
    'api_documentation.update' => '更新',
    'api_documentation.delete' => '删除',
    'api_documentation.allowed_values' => '允许的值：%s',
    'api_documentation.available_when' => '可用时机：%s',
    'api_documentation.timezone_info' => '除非另有说明，否则所有API端点结果都使用<strong>%s时区</strong>。',

    'api_documentation.authentication.header' => '认证',
    'api_documentation.authentication.subheader' => '所有API端点都需要通过<strong>Bearer身份验证方法</strong>发送API密钥。',

    'api_documentation.filters.page' => '您想要结果的页码。默认为<code>1</code>。',
    'api_documentation.filters.results_per_page' => '您希望每页有多少结果。允许的值为：%1$s。默认为<code>%2$s</code>。',
    'api_documentation.filters.search' => '搜索字符串。',
    'api_documentation.filters.search_by' => '您按哪个字段搜索。允许的值为：%s。',
    'api_documentation.filters.order_by' => '按哪个字段对结果进行排序。允许的值为：%s。',
    'api_documentation.filters.order_by_type' => '结果的排序方式。允许的值为：<code>ASC</code>表示升序，<code>DESC</code>表示降序。',

    'api_documentation.team_members' => '团队成员',
    'api_documentation.teams_member' => '团队成员',
    'api_documentation.user' => '用户',

    'api_documentation.statistics' => '网站统计数据',
    'api_documentation.statistics.start_date' => '开始日期，格式为<code>Y-m-d</code>。',
    'api_documentation.statistics.end_date' => '结束日期，格式为<code>Y-m-d</code>。',

    'api_documentation.websites' => '网站',
    'api_documentation.websites.host' => '示例：<code>example.com/path</code>。',
    'api_documentation.websites.excluded_ips' => '从跟踪中排除IP。输入逗号分隔的值。',
    'api_documentation.websites.events_children_is_enabled' => '跟踪访客事件（鼠标点击、调整大小、滚动、表单提交）。允许的值为：<code>0</code>或<code>1</code>。仅适用于<code>normal</code>跟踪类型。',
    'api_documentation.websites.sessions_replays_is_enabled' => '会话重放。允许的值为：<code>0</code>或<code>1</code>。仅适用于<code>normal</code>跟踪类型。',
    'api_documentation.websites.email_reports_is_enabled' => '电子邮件报告。允许的值为：<code>0</code>或<code>1</code>。',

    'contact.breadcrumb' => '联系',
    'contact.title' => '联系',
    'contact.menu' => '联系',
    'contact.header' => '联系我们',
    'contact.subheader' => '通过电子邮件与我们联系。',
    'contact.email' => '电子邮件地址',
    'contact.name' => '全名',
    'contact.subject' => '主题',
    'contact.message' => '消息',
    'contact.success_message' => '您的消息已发送！我们会尽快回复您。',

    'internal_notifications.breadcrumb' => '通知',
    'internal_notifications.title' => '通知',
    'internal_notifications.menu' => '通知',
    'internal_notifications.header' => '通知',
    'internal_notifications.subheader' => '您所有最近的与帐户相关的通知。',
    'internal_notifications.no_data' => '没有可用的通知',

    'affiliate.breadcrumb' => '联盟',
    'affiliate.title' => '联盟',
    'affiliate.menu' => '联盟',
    'affiliate.header' => '联盟计划',
    'affiliate.subheader' => '从您带到平台的人那里赚取佣金的最简单方法。',

    'affiliate.commission_percentage.header' => '%s 佣金',
    'affiliate.commission_percentage.subheader_once' => '从您带到平台的任何用户的首次付款中赚取佣金。',
    'affiliate.commission_percentage.subheader_forever' => '从您带到平台的任何用户的所有付款中赚取佣金。',

    'affiliate.minimum_withdrawal_amount.header' => '%s 最低提款额',
    'affiliate.minimum_withdrawal_amount.subheader' => '一旦您的已批准余额达到最低提款额，您就可以请求提款。',

    'affiliate.how.header' => '它是如何工作的？',
    'affiliate.how.one' => '注册',
    'affiliate.how.one_help' => '只需在我们的平台上注册一个帐户。',
    'affiliate.how.two' => '分享您的链接',
    'affiliate.how.two_help' => '开始推广您的推荐链接并带来新用户。',
    'affiliate.how.three' => '开始赚钱',
    'affiliate.how.three_help' => '一旦您推荐的用户开始付款，您也将获得报酬。',
    'affiliate.how.four' => '提取您的钱',
    'affiliate.how.four_help' => '请求提款，您将获得报酬。',

    'affiliate.cta.header' => '开始赚钱 💰',
    'affiliate.cta.subheader' => '创建一个帐户，只需几分钟即可开始。',
    'affiliate.cta.register' => '注册',

    'not_found.title' => '未找到',
    'not_found.header' => '页面未找到',
    'not_found.subheader' => '抱歉，我们找不到您正在寻找的页面。',
    'not_found.button' => '返回主页',

    'cron.email_reports.title' => '{{WEBSITE:NAME}}在{{START_DATE}}和{{END_DATE}}之间的摘要分析 - {{WEBSITE_TITLE}}',
    'cron.email_reports.p1' => '<strong>%s</strong>网站上发生的事情的简短分析概述。',
    'cron.email_reports.button' => '查看分析',
    'cron.email_reports.notice' => '您收到这些电子邮件是因为您激活了电子邮件报告。您可以随时在%s网站设置%s页面退订。',
];