<?php
/*
 * Copyright (c) 2025 AltumCode (https://altumcode.com/)
 *
 * This software is licensed exclusively by AltumCode and is sold only via https://altumcode.com/.
 * Unauthorized distribution, modification, or use of this software without a valid license is not permitted and may be subject to applicable legal actions.
 *
 * 🌍 View all other existing AltumCode projects via https://altumcode.com/
 * 📧 Get in touch for support or general queries via https://altumcode.com/contact
 * 📤 Download the latest version via https://altumcode.com/downloads
 *
 * 🐦 X/Twitter: https://x.com/AltumCode
 * 📘 Facebook: https://facebook.com/altumcode
 * 📸 Instagram: https://instagram.com/altumcode
 */

return [
    'admin_blog.menu' => '博客',
    'admin_blog.advanced' => '高级设置',
    'admin_blog.title' => '标题',
    'admin_blog.keywords' => 'Meta关键词',
    'admin_blog.keywords_help' => '逗号分隔的关键词 (关键词1, 关键词2..等)',
    'admin_blog.image' => '特色图片',
    'admin_blog.order_help' => '通过数字按升序轻松排列页面。',
    'admin_blog.blog_posts_category_id' => '分类',
    'admin_blog.image_description' => '图片描述',
    'admin_blog.editor' => '编辑器',
    'admin_blog.editor_raw' => '无编辑器',
    'admin_blog.editor_wysiwyg' => '所见即所得',
    'admin_blog.editor_blocks' => '区块',
    'admin_blog.editor_confirm' => '切换编辑器可能会导致您已有的内容丢失。',
    'admin_blog.content' => '内容',
    'admin_blog.is_published' => '已发布',
    'admin_blog.error_message.url_exists' => '此URL别名已被占用。',
    'admin_blog.warning_message.disabled' => '博客系统当前已禁用。请从 %s网站设置页面%s 启用它。',


    'admin_blog_posts.breadcrumb' => '博客文章',
    'admin_blog_posts.title' => '博客文章',
    'admin_blog_posts.menu' => '文章',
    'admin_blog_posts.header' => '博客文章',
    'admin_blog_posts.header_no_data' => '创建您的第一篇博客文章',
    'admin_blog_posts.subheader_no_data' => '为您的用户创建信息丰富、有帮助且高质量的内容。',
    'admin_blog_posts.create' => '创建文章',
    'admin_blog_posts.total_views' => '%s 次浏览',
    'admin_blog_posts.total_ratings' => '%s 个评分',
    'admin_blog_posts.average_rating' => '%s 平均评分',
    'admin_blog_posts.table.blog_post' => '文章',


    'admin_blog_post_create.breadcrumb' => '创建博客文章',
    'admin_blog_post_create.title' => '创建博客文章',
    'admin_blog_post_create.header' => '创建博客文章',


    'admin_blog_post_update.breadcrumb' => '编辑博客文章',
    'admin_blog_post_update.title' => '编辑博客文章',
    'admin_blog_post_update.header' => '编辑博客文章',


    'admin_blog_posts_categories.breadcrumb' => '博客文章分类',
    'admin_blog_posts_categories.title' => '博客文章分类',
    'admin_blog_posts_categories.menu' => '分类',
    'admin_blog_posts_categories.header' => '博客文章分类',
    'admin_blog_posts_categories.header_no_data' => '创建您的第一个博客文章分类',
    'admin_blog_posts_categories.subheader_no_data' => '轻松地分离和分类您的博客文章。',
    'admin_blog_posts_categories.create' => '创建分类',
    'admin_blog_posts_categories.table.blog_posts_category' => '分类',
    'admin_blog_posts_categories.table.blog_posts' => '查看博客文章',


    'admin_blog_posts_category_create.breadcrumb' => '创建分类',
    'admin_blog_posts_category_create.title' => '创建分类',
    'admin_blog_posts_category_create.header' => '创建分类',


    'admin_blog_posts_category_update.breadcrumb' => '编辑分类',
    'admin_blog_posts_category_update.title' => '编辑分类',
    'admin_blog_posts_category_update.header' => '编辑分类',


    'admin_resources.menu' => '资源',
    'admin_resources.advanced' => '高级设置',
    'admin_resources.title' => '标题',
    'admin_resources.keywords' => 'Meta关键词',
    'admin_resources.keywords_help' => '逗号分隔的关键词 (关键词1, 关键词2..等)',
    'admin_resources.open_in_new_tab' => '在新标签页中打开',
    'admin_resources.editor' => '编辑器',
    'admin_resources.editor_raw' => '无编辑器',
    'admin_resources.editor_wysiwyg' => '所见即所得',
    'admin_resources.editor_blocks' => '区块',
    'admin_resources.editor_confirm' => '切换编辑器可能会导致您已有的内容丢失。',
    'admin_resources.content' => '内容',
    'admin_resources.position' => '位置',
    'admin_resources.position_top' => '顶部菜单',
    'admin_resources.position_bottom' => '底部菜单',
    'admin_resources.position_hidden' => '隐藏',
    'admin_resources.type_internal' => '页面',
    'admin_resources.type_external' => '链接',
    'admin_resources.pages_category_id' => '分类',
    'admin_resources.order_help' => '通过数字按升序轻松排列。',
    'admin_resources.is_published' => '已发布',
    'admin_resources.error_message.url_exists' => '此URL别名已被占用。',
    'admin_resources.warning_message.disabled' => '页面系统当前已禁用。请从 %s网站设置页面%s 启用它。',


    'admin_pages.breadcrumb' => '页面',
    'admin_pages.title' => '页面',
    'admin_pages.menu' => '页面',
    'admin_pages.header' => '页面',
    'admin_pages.header_no_data' => '创建您的第一个页面',
    'admin_pages.subheader_no_data' => '轻松创建可以附加到平台的额外页面。',
    'admin_pages.create' => '创建页面',
    'admin_pages.table.page' => '页面',
    'admin_pages.table.total_views' => '%s 次浏览',


    'admin_page_create.breadcrumb' => '创建页面',
    'admin_page_create.title' => '创建页面',
    'admin_page_create.header' => '创建页面',


    'admin_page_update.breadcrumb' => '编辑页面',
    'admin_page_update.title' => '编辑页面',
    'admin_page_update.header' => '编辑页面',


    'admin_pages_categories.breadcrumb' => '页面分类',
    'admin_pages_categories.menu' => '分类',
    'admin_pages_categories.title' => '页面分类',
    'admin_pages_categories.header' => '页面分类',
    'admin_pages_categories.header_no_data' => '创建您的第一个页面分类',
    'admin_pages_categories.subheader_no_data' => '按分类对您的附加页面进行排序。',
    'admin_pages_categories.create' => '创建分类',
    'admin_pages_categories.table.pages_category' => '分类',
    'admin_pages_categories.table.pages' => '查看页面',


    'admin_pages_category_create.breadcrumb' => '创建页面分类',
    'admin_pages_category_create.title' => '创建页面分类',
    'admin_pages_category_create.header' => '创建一个新的页面分类',


    'admin_pages_category_update.breadcrumb' => '编辑页面分类',
    'admin_pages_category_update.title' => '编辑页面分类',
    'admin_pages_category_update.header' => '编辑页面分类',


    'admin_plans.breadcrumb' => '计划',
    'admin_plans.title' => '计划',
    'admin_plans.menu' => '计划',
    'admin_plans.header' => '计划',
    'admin_plans.create' => '创建计划',

    'admin_plans.table.name' => '计划名称',
    'admin_plans.table.custom_help' => '自定义计划可以直接从用户编辑页面定义。',
    'admin_plans.table.price' => '价格',
    'admin_plans.table.users' => '用户',

    'admin_plans.plan_id' => '计划ID',
    'admin_plans.price' => '价格',
    'admin_plans.custom_contact_value' => '联系按钮值',
    'admin_plans.custom_button_url' => '联系按钮URL',
    'admin_plans.monthly_price' => '月度价格',
    'admin_plans.quarterly_price' => '季度价格',
    'admin_plans.biannual_price' => '半年度价格',
    'admin_plans.annual_price' => '年度价格',
    'admin_plans.lifetime_price' => '终身套餐价格',
    'admin_plans.price_help' => '设置为0以禁用 %s',
    'admin_plans.color' => '颜色',
    'admin_plans.color_help' => '设置颜色以突出显示计划，留空为默认颜色。',
    'admin_plans.taxes_ids' => '应用的税费',
    'admin_plans.taxes_ids_help' => '轻松选择您想要在每个计划上应用的%s已创建的税费%s。',
    'admin_plans.trial_days' => '试用天数',
    'admin_plans.trial_days_help' => '如果您不想为此计划提供试用，请设置为0。',
    'admin_plans.custom_help' => '<strong>更新此计划不会影响任何使用自定义计划的用户。</strong> 如果您想编辑特定用户的自定义计划，请改用用户更新页面。它只会影响前端计划部分显示的计划。',

    'admin_plans.plan.header' => '计划功能',
    'admin_plans.plan.per_month' => '每月，每个网站',
    'admin_plans.plan.unlimited' => '设置为-1表示无限制。',
    'admin_plans.plan.retention_help' => '数据将在数据库中保留多少天。',
    'admin_plans.plan.websites_limit' => '网站限制',
    'admin_plans.plan.sessions_events_limit' => '页面浏览量限制',
    'admin_plans.plan.sessions_events_retention' => '页面浏览数据保留',
    'admin_plans.plan.events_children_limit' => '访客事件限制',
    'admin_plans.plan.events_children_limit_help' => '跟踪网站上用户的行为，例如（点击、调整大小、表单提交等）。设置为0以禁用此功能，设置为-1表示无限制。',
    'admin_plans.plan.events_children_retention' => '访客事件数据保留',
    'admin_plans.plan.sessions_replays_limit' => '视频重放限制',
    'admin_plans.plan.sessions_replays_limit_help' => '全面和高级地跟踪网站上用户的行为，并能够重放这些操作。设置为0以禁用此功能，设置为-1表示无限制。',
    'admin_plans.plan.sessions_replays_retention' => '视频重放数据保留',
    'admin_plans.plan.sessions_replays_time_limit' => '视频重放时间限制',
    'admin_plans.plan.sessions_replays_time_limit_help' => '会话重放将记录事件的最大分钟数。',
    'admin_plans.plan.websites_heatmaps_limit' => '热图限制',
    'admin_plans.plan.websites_heatmaps_limit_help' => '用户可以创建多少个热图。设置为0以禁用此功能，设置为-1表示无限制。',
    'admin_plans.plan.websites_goals_limit' => '目标限制',
    'admin_plans.plan.websites_goals_limit_help' => '允许用户使用目标功能跟踪其网站目标。设置为0以禁用此功能，设置为-1表示无限制。',
    'admin_plans.plan.domains_limit' => '自定义域名限制',
    'admin_plans.plan.no_ads' => '无广告',
    'admin_plans.plan.no_ads_help' => '启用此项将使所有拥有此计划的人看不到任何广告。',
    'admin_plans.plan.export' => '启用的导出选项',
    'admin_plans.plan.email_reports_is_enabled' => '电子邮件报告',
    'admin_plans.plan.email_reports_is_enabled_help' => '启用此项将使所有拥有此计划的人能够为其网站启用电子邮件报告。',
    'admin_plans.plan.teams_is_enabled' => '团队系统',
    'admin_plans.plan.teams_is_enabled_help' => '启用此项将使所有拥有此计划的人能够使用团队系统创建和邀请人员加入他们的团队。',
    'admin_plans.plan.api_is_enabled' => 'API访问',
    'admin_plans.plan.api_is_enabled_help' => '使用户能够使用REST API。',
    'admin_plans.plan.white_labeling_is_enabled' => '白标',
    'admin_plans.plan.white_labeling_is_enabled_help' => '使用户能够更改其帐户的标题、徽标、网站图标和页脚。',
    'admin_plans.plan.affiliate_commission_percentage' => '联盟佣金百分比',
    'admin_plans.plan.affiliate_commission_percentage_help' => '设置为0以禁止用户使用此功能。',


    'admin_plan_delete_modal.header' => '删除计划',
    'admin_plan_delete_modal.subheader' => '删除该计划后，此计划的所有定期订阅将被取消。用户仍将拥有他们已付费的功能，直到计划的到期日。此操作无法撤销。',


    'admin_plan_create.breadcrumb' => '创建计划',
    'admin_plan_create.title' => '创建计划',
    'admin_plan_create.menu' => '创建计划',
    'admin_plan_create.header' => '创建一个新计划',


    'admin_plan_update.breadcrumb' => '编辑计划',
    'admin_plan_update.title' => '编辑计划',
    'admin_plan_update.header' => '编辑计划',
    'admin_plan_update.update_users_plan_settings.button' => '同时更新计划订阅者',
    'admin_plan_update.update_users_plan_settings.button_help' => '通过更新计划订阅者，您将用此计划的新设置覆盖他们所有当前的设置。',
    'admin_plan_update.error_message.disabled_plans' => '您不能禁用所有可用的计划（如果支付系统已禁用，则不考虑自定义计划）。',

    'admin_codes.breadcrumb' => '代码',
    'admin_codes.title' => '代码',
    'admin_codes.menu' => '代码',
    'admin_codes.header' => '代码',
    'admin_codes.header_no_data' => '创建您的第一个代码',
    'admin_codes.subheader_no_data' => '创建折扣代码或完全可兑换的代码，您可以与用户共享。',
    'admin_codes.create' => '创建代码',

    'admin_codes.type_discount' => '折扣',
    'admin_codes.type_redeemable' => '可兑换',
    'admin_codes.days' => '天数',
    'admin_codes.days_help' => '计划将可用多少天。任何超过10年（3650天）的值将作为终身计划显示给用户。',
    'admin_codes.code' => '代码',
    'admin_codes.discount' => '折扣',
    'admin_codes.discount_help' => '为代码选择1%到99%的折扣',
    'admin_codes.quantity' => '数量',
    'admin_codes.quantity_help' => '代码可以被使用的次数。',
    'admin_codes.is_bulk' => '批量生成器',
    'admin_codes.amount' => '唯一代码数量',
    'admin_codes.prefix' => '生成的唯一代码前缀',
    'admin_codes.redeemed' => '已兑换',
    'admin_codes.plans_ids' => '计划',


    'admin_code_create.breadcrumb' => '创建代码',
    'admin_code_create.title' => '创建代码',
    'admin_code_create.menu' => '创建代码',
    'admin_code_create.header' => '创建一个新代码',

    'admin_code_update.breadcrumb' => '编辑代码',
    'admin_code_update.title' => '编辑代码',
    'admin_code_update.header' => '编辑代码',
    'admin_code_update.subheader' => '更改设置不会对已经兑换或使用的代码产生任何影响。',
    'admin_code_update.subheader2' => '您可以使用可共享链接共享代码：%s',

    'admin_taxes.breadcrumb' => '税费',
    'admin_taxes.title' => '税费',
    'admin_taxes.menu' => '税费',
    'admin_taxes.header' => '税费',
    'admin_taxes.header_no_data' => '创建您的第一项税费',
    'admin_taxes.subheader_no_data' => '创建您可以用于并应用于付费计划的税费。',
    'admin_taxes.create' => '创建税费',
    'admin_taxes.tax' => '税费',
    'admin_taxes.value' => '税值',
    'admin_taxes.value_type' => '值类型',
    'admin_taxes.value_type_percentage' => '百分比',
    'admin_taxes.value_type_fixed' => '固定值',
    'admin_taxes.type_inclusive' => '包含式',
    'admin_taxes.type_exclusive' => '排除式',
    'admin_taxes.billing_type' => '账单对象',
    'admin_taxes.billing_type_personal' => '仅个人',
    'admin_taxes.billing_type_business' => '仅企业',
    'admin_taxes.billing_type_both' => '个人和企业',
    'admin_taxes.billing_type_help' => '选择您希望为此税费应用的对象。',
    'admin_taxes.countries_help' => '选择您希望应用此税费的国家。留空则表示对所有国家应用。',

    'admin_tax_create.breadcrumb' => '创建税费',
    'admin_tax_create.title' => '创建税费',
    'admin_tax_create.menu' => '创建税费',
    'admin_tax_create.header' => '创建一个新税费',
    'admin_tax_create.subheader' => '一旦创建了税费，就不能编辑或删除。创建税费后，您可以将其与您创建的计划关联起来。',

    'admin_tax_update.breadcrumb' => '编辑税费',
    'admin_tax_update.title' => '编辑税费',
    'admin_tax_update.header' => '编辑税费',


    'admin_tax_delete_modal.header' => '删除税费',
    'admin_tax_delete_modal.subheader' => '如果您在删除此税费的同时，它正被用于先前注册的付款，您将丢失重要的发票数据。此操作无法撤销。',


    'admin_affiliates_withdrawals.title' => '联盟提款',
    'admin_affiliates_withdrawals.menu' => '联盟提款',
    'admin_affiliates_withdrawals.header' => '联盟提款',

    'admin_affiliates_withdrawals.amount' => '金额',
    'admin_affiliates_withdrawals.is_paid' => '已支付',
    'admin_affiliates_withdrawals.is_paid_paid' => '已支付',
    'admin_affiliates_withdrawals.is_paid_pending' => '待处理',
    'admin_affiliates_withdrawals.action_pay_affiliate_withdrawal' => '批准提款',


    'admin_affiliate_withdrawal_approve_modal.header' => '批准提款',
    'admin_affiliate_withdrawal_approve_modal.subheader' => '如果您批准提款，联盟提款将被视为已完成，用户将通过电子邮件收到通知。别忘了发送他们的付款。',
    'admin_affiliate_withdrawal_approve_modal.success_message' => '联盟提款请求已获批准。',


    'admin_payments.title' => '付款列表',
    'admin_payments.header' => '付款列表',
    'admin_payments.menu' => '付款',

    'admin_payments.plan' => '计划',
    'admin_payments.total_amount' => '总金额',
    'admin_payments.action_view_proof' => '查看凭证',
    'admin_payments.action_approve_proof' => '批准付款',
    'admin_payments.invoice' => '发票',

    'admin_payments.filters.status_paid' => '已支付',
    'admin_payments.filters.status_pending' => '待处理',
    'admin_payments.filters.plan_id' => '计划',
    'admin_payments.filters.search_by_payment_id' => '外部付款ID',
    'admin_payments.filters.order_by_total_amount' => '总金额',


    'admin_payment_approve_modal.header' => '批准付款',
    'admin_payment_approve_modal.subheader' => '如果您批准付款，用户的计划将开始。',
    'admin_payment_approve_modal.success_message' => '付款批准已成功执行。',

    'admin_index.title' => '管理后台',
    'admin_index.menu' => '管理后台',
    'admin_index.header' => '欢迎回来, %s 👋',
    'admin_index.users' => '最新用户',
    'admin_index.active_users' => '%s 位在线用户',
    'admin_index.active_users_tooltip' => '过去15分钟内。',
    'admin_index.payments' => '最新付款',
    'admin_index.payments_total_amount' => '收入',
    'admin_index.admins_notifications' => '管理员通知',
    'admin_index.goals' => '目标',

    'admin_users.breadcrumb' => '用户',
    'admin_users.title' => '用户',
    'admin_users.header' => '用户',
    'admin_users.menu' => '用户',
    'admin_users.table.total_logins' => '总登录次数: %s',


    'admin_users.user_id' => '用户ID',
    'admin_users.plan_id' => '计划',
    'admin_users.plan_expiration_date' => '计划到期日',
    'admin_users.type' => '权限',
    'admin_users.type_help' => '管理员用户将拥有与您相同的权限，请小心！',
    'admin_users.type_admin' => '管理员',
    'admin_users.type_user' => '用户',
    'admin_users.source' => '来源',
    'admin_users.source.direct' => '直接注册',
    'admin_users.source.admin_create' => '管理员创建',
    'admin_users.source.admin_api_create' => '管理员API创建',
    'admin_users.source.facebook' => 'Facebook登录',
    'admin_users.source.google' => 'Google登录',
    'admin_users.source.discord' => 'Discord登录',
    'admin_users.source.twitter' => 'X登录',
    'admin_users.source.linkedin' => 'LinkedIn登录',
    'admin_users.source.microsoft' => 'Microsoft登录',
    'admin_users.status_active' => '活跃',
    'admin_users.status_disabled' => '禁用',
    'admin_users.status_unconfirmed' => '未确认',
    'admin_users.datetime' => '注册日期',
    'admin_users.total_logins' => '总登录次数',
    'admin_users.api_key' => 'API密钥',
    'admin_users.last_activity' => '最后活跃',
    'admin_users.plan_trial_done' => '试用已结束',
    'admin_users.plan_expiry_reminder' => '已发送计划到期提醒',
    'admin_users.payment_subscription_id' => '最后订阅ID',
    'admin_users.payment_processor' => '最后付款处理器',
    'admin_users.payment_total_amount' => '最后付款金额',
    'admin_users.referral_key' => '推荐密钥',
    'admin_users.referred_by' => '推荐人',
    'admin_users.referred_by_has_converted' => '已转化推荐',
    'admin_users.timezone' => '时区',
    'admin_users.twofa_is_enabled' => '双因素认证',
    'admin_users.anti_phishing_code' => '防钓鱼码',
    'admin_users.user_deletion_reminder' => '已发送用户删除提醒',
    'admin_users.is_newsletter_subscribed' => '已订阅新闻通讯',

    'admin_users.error_message.self_delete' => '您不能删除自己！',
    'admin_users.error_message.name_length' => '名称字段长度必须在1到64个字符之间！',
    'admin_users.error_message.email_exists' => '此电子邮件已被另一个帐户使用！',


    'admin_user_login_modal.header' => '以此用户身份登录',
    'admin_user_login_modal.subheader' => '以此用户身份登录后，您将从当前帐户登出并完全登录到此用户。',
    'admin_user_login_modal.success_message' => '成功以 %s 的身份登录！要退出此帐户，只需使用登出功能。',
    'admin_user_login_modal.error_message.disabled' => '只有当用户状态为活跃时，您才能登录。',

    'admin_user_create.breadcrumb' => '创建用户',
    'admin_user_create.title' => '创建用户',
    'admin_user_create.header' => '创建用户',
    'admin_user_create.menu' => '创建用户',

    'admin_user_update.breadcrumb' => '编辑用户',
    'admin_user_update.title' => '编辑用户',
    'admin_user_update.header' => '编辑用户',

    'admin_user_update.plan.header' => '计划',
    'admin_user_update.plan.settings' => '计划设置',
    'admin_user_update.plan.plan_expiration_date_invalid' => '您必须将计划到期日期设置在将来某个时间。',

    'admin_user_update.change_password.header' => '更改密码',
    'admin_user_update.change_password.subheader' => '如果您不想更改密码，请留空。',
    'admin_user_update.change_password.new_password' => '新密码',
    'admin_user_update.change_password.repeat_password' => '重复密码',

    'admin_user_view.breadcrumb' => '查看用户',
    'admin_user_view.title' => '查看用户',
    'admin_user_view.header' => '查看用户',
    'admin_user_view.billing' => '账单详情',
    'admin_user_view.referred_by' => '推荐',
    'admin_user_view.email_reports' => '电子邮件报告',
    'admin_user_view.teams' => '团队',
    'admin_user_view.teams_associations' => '用户所属的团队',


    'admin_users_logs.title' => '用户日志',
    'admin_users_logs.header' => '用户日志',
    'admin_users_logs.menu' => '用户日志',


    'admin_internal_notifications.breadcrumb' => '用户通知',
    'admin_internal_notifications.title' => '用户通知',
    'admin_internal_notifications.header' => '用户通知',
    'admin_internal_notifications.header_no_data' => '创建您的通知广播',
    'admin_internal_notifications.subheader_no_data' => '向您的用户发送信息性消息、优惠和任何类型的消息。',
    'admin_internal_notifications.menu' => '用户通知',
    'admin_internal_notifications.create' => '创建通知',
    'admin_internal_notifications.table.internal_notification' => '通知',
    'admin_internal_notifications.from_who' => '来自',
    'admin_internal_notifications.from_who.system' => '系统',
    'admin_internal_notifications.from_who.admin' => '管理员',
    'admin_internal_notifications.for_who' => '为谁',
    'admin_internal_notifications.for_who.user' => '用户',
    'admin_internal_notifications.for_who.admin' => '管理员',
    'admin_internal_notifications.is_read' => '已读',
    'admin_internal_notifications.read_datetime' => '于 %s 阅读',
    'admin_internal_notifications.filters.read_datetime' => '阅读日期时间',


    'admin_internal_notification_create.breadcrumb' => '创建通知',
    'admin_internal_notification_create.title' => '创建通知',
    'admin_internal_notification_create.menu' => '创建通知',
    'admin_internal_notification_create.header' => '创建一个新通知',
    'admin_internal_notification_create.send' => '发送通知',


    'admin_push_notifications.breadcrumb' => '推送通知',
    'admin_push_notifications.title' => '推送通知',
    'admin_push_notifications.header' => '推送通知',
    'admin_push_notifications.header_no_data' => '创建您的通知广播',
    'admin_push_notifications.subheader_no_data' => '向您的用户发送信息性消息、优惠和任何类型的消息。',
    'admin_push_notifications.menu' => '推送通知',
    'admin_push_notifications.create' => '创建通知',
    'admin_push_notifications.table.push_notification' => '通知',
    'admin_push_notifications.main.title' => '标题',
    'admin_push_notifications.main.total_push_notifications' => '总推送通知',
    'admin_push_notifications.main.sent_push_notifications' => '已发送推送通知',
    'admin_push_notifications.main.push_subscribers_ids' => '推送订阅者ID',
    'admin_push_notifications.main.push_subscribers_ids_placeholder' => '1,2,3',
    'admin_push_notifications.main.push_subscribers_ids_help' => '逗号分隔的值。',
    'admin_push_notifications.main.segment' => '分段',
    'admin_push_notifications.main.segment.all' => '所有订阅者',
    'admin_push_notifications.main.segment.custom' => '自定义',
    'admin_push_notifications.main.segment.filter' => '筛选',
    'admin_push_notifications.main.segment.filter.is_registered' => '是否注册？',
    'admin_push_notifications.main.status.draft' => '草稿',
    'admin_push_notifications.main.status.processing' => '处理中',
    'admin_push_notifications.main.status.sent' => '已发送',
    'admin_push_notifications.main.last_sent_datetime' => '上次发送通知 %s',

    'admin_push_notification_create.breadcrumb' => '创建通知',
    'admin_push_notification_create.title' => '创建通知',
    'admin_push_notification_create.menu' => '创建通知',
    'admin_push_notification_create.header' => '创建一个新通知',
    'admin_push_notification_create.save' => '保存草稿',
    'admin_push_notification_create.send' => '发送通知',
    'admin_push_notification_create.success_message.save' => '%s 通知已保存。您可以稍后回来发送它。',
    'admin_push_notification_create.success_message.send' => '%s 通知将开始处理。',


    'admin_push_notification_update.breadcrumb' => '更新通知',
    'admin_push_notification_update.title' => '更新通知',
    'admin_push_notification_update.menu' => '更新通知',
    'admin_push_notification_update.header' => '更新通知',
    'admin_push_notification_update.error_message.processing' => '您不能在处理推送通知时查看或更新它。',


    'admin_push_subscribers.breadcrumb' => '推送订阅者',
    'admin_push_subscribers.title' => '推送订阅者',
    'admin_push_subscribers.header' => '推送订阅者',
    'admin_push_subscribers.header_no_data' => '无推送订阅者',
    'admin_push_subscribers.subheader_no_data' => '目前没有推送订阅者，当您有一些时，您将在这里看到一个列表。',
    'admin_push_subscribers.menu' => '推送订阅者',
    'admin_push_subscribers.table.push_subscriber' => '推送订阅者',


    'admin_redeemed_codes.title' => '已兑换代码',
    'admin_redeemed_codes.header' => '已兑换代码',
    'admin_redeemed_codes.menu' => '已兑换代码',
    'admin_redeemed_codes.table.code' => '代码',


    'admin_settings.title' => '设置 - %s',
    'admin_settings.menu' => '设置',
    'admin_settings.header' => '设置 - %s',
    'admin_settings.documentation' => '阅读%s文档%s以获取更多详情。',
    'admin_settings.payment_processors' => '支付处理器',
    'admin_settings.social_logins' => '社交登录',
    'admin_settings.social_logins.callback_url' => '回调URL',

    'admin_settings.main.tab' => '主要',
    'admin_settings.main.index_settings' => '首页设置',
    'admin_settings.main.app_settings' => '全站设置',
    'admin_settings.main.other_settings' => '其他设置',
    'admin_settings.main.maintenance_settings' => '维护设置',
    'admin_settings.main.admin_spotlight_is_enabled' => '为管理员启用聚光灯系统',
    'admin_settings.main.admin_spotlight_is_enabled_help' => '能够使用全局搜索模态框通过CMD/CTRL + K轻松地从一个页面跳转到另一个页面。',
    'admin_settings.main.user_spotlight_is_enabled' => '为用户启用聚光灯系统',
    'admin_settings.main.user_spotlight_is_enabled_help' => '能够使用全局搜索模态框通过CMD/CTRL + K轻松地从一个页面跳转到另一个页面。',
    'admin_settings.main.white_labeling_is_enabled' => '启用白标系统',
    'admin_settings.main.white_labeling_is_enabled_help' => '允许具有白标功能的用户自定义其帐户的标题、徽标和页脚。',
    'admin_settings.main.chart_cache' => '预览图表缓存',
    'admin_settings.main.chart_days' => '预览图表时间范围',
    'admin_settings.main.title' => '网站标题',
    'admin_settings.main.default_language' => '默认语言',
    'admin_settings.main.default_theme_style' => '默认主题样式',
    'admin_settings.main.theme_style_change_is_enabled' => '启用主题样式选择器',
    'admin_settings.main.theme_style_change_is_enabled_help' => '在前端页脚向用户显示主题样式选择器按钮。',
    'admin_settings.main.logo_light' => '浅色主题徽标',
    'admin_settings.main.logo_dark' => '深色主题徽标',
    'admin_settings.main.logo_email' => '发送邮件的徽标',
    'admin_settings.main.favicon' => '网站图标',
    'admin_settings.main.opengraph' => 'Opengraph图片',
    'admin_settings.main.ai_scraping_is_allowed' => '允许AI抓取',
    'admin_settings.main.ai_scraping_is_allowed_help' => '允许AI使用您网站的可抓取内容进行学习（OpenAI, Bing, Google）。',
    'admin_settings.main.iframe_embedding' => '允许Iframe嵌入的域名',
    'admin_settings.main.iframe_embedding_help' => '允许您的网站被特定域名嵌入。使用“none”完全禁用iframe嵌入。使用“all”允许所有域名嵌入。输入您想要允许的域名URL，用逗号分隔。',
    'admin_settings.main.se_indexing' => '允许搜索引擎索引',
    'admin_settings.main.display_index_plans' => '在首页显示计划',
    'admin_settings.main.display_index_testimonials' => '在首页显示推荐',
    'admin_settings.main.display_index_faq' => '在首页显示FAQ',
    'admin_settings.main.display_index_latest_blog_posts' => '在首页显示最新博客文章',
    'admin_settings.main.default_timezone' => '默认时区',
    'admin_settings.main.default_timezone_help' => '用户注册时的默认时区（他们以后可以更改）。',
    'admin_settings.main.index_url' => '自定义首页URL',
    'admin_settings.main.index_url_help' => '禁用原始着陆页并重定向到一个新的页面。留空以禁用。',
    'admin_settings.main.not_found_url' => '自定义404页面URL',
    'admin_settings.main.not_found_url_help' => '禁用原始404未找到页面并重定向到一个新的页面。留空以禁用。',
    'admin_settings.main.terms_and_conditions_url' => '条款和条件URL',
    'admin_settings.main.terms_and_conditions_url_help' => '网站的条款和条件链接。它将在用户注册和付款时显示。',
    'admin_settings.main.privacy_policy_url' => '隐私政策URL',
    'admin_settings.main.privacy_policy_url_help' => '网站的隐私政策链接。它将在用户注册和付款时显示。',
    'admin_settings.main.default_results_per_page' => '默认每页结果数',
    'admin_settings.main.default_order_type' => '默认结果排序',
    'admin_settings.main.auto_language_detection_is_enabled' => '启用自动语言检测',
    'admin_settings.main.auto_language_detection_is_enabled_help' => '您的访问者将被自动重定向到其浏览器的语言，如果该特定语言在您的网站上可用。',
    'admin_settings.main.api_is_enabled' => '启用用户API系统',
    'admin_settings.main.openai_api_key' => 'OpenAI API密钥',
    'admin_settings.main.openai_api_key_help' => '此字段仅用于在管理面板中自动翻译语言包。',
    'admin_settings.main.openai_model' => 'OpenAI模型',
    'admin_settings.main.sitemap_url' => '站点地图URL',
    'admin_settings.main.force_https_is_enabled' => '强制HTTPS',
    'admin_settings.main.force_https_is_enabled_help' => '您的config.php SITE_URL是：<code>%s</code>。只有在确保您的config.php文件的SITE_URL值以<code>https://</code>开头后才启用此功能。',
    'admin_settings.main.broadcasts_statistics_is_enabled' => '跟踪广播的电子邮件浏览和点击',
    'admin_settings.main.broadcasts_statistics_is_enabled_help' => '启用此功能会增加您服务器和数据库存储的负载。',
    'admin_settings.main.breadcrumbs_is_enabled' => '启用面包屑导航',
    'admin_settings.main.breadcrumbs_is_enabled_help' => '面包屑是大多数页面上方的小链接，可帮助您导航返回并更好地了解您所在的位置。',
    'admin_settings.main.display_pagination_when_no_pages' => '无论页面数量如何都显示分页',
    'admin_settings.main.display_pagination_when_no_pages_help' => '如果禁用 - 分页按钮仅在至少有2页可用时显示。',
    'admin_settings.main.maintenance_is_enabled' => '启用维护模式',
    'admin_settings.main.maintenance_is_enabled_help' => '除登录、忘记密码和重置密码页面外，所有页面对您的用户（管理员除外）都将无法访问。',
    'admin_settings.main.maintenance_title' => '维护标题',
    'admin_settings.main.maintenance_description' => '维护描述',
    'admin_settings.main.maintenance_button_text' => '操作按钮文本',
    'admin_settings.main.maintenance_button_url' => '操作按钮URL',

    'admin_settings.users.tab' => '用户',
    'admin_settings.users.welcome_email_is_enabled' => '欢迎邮件',
    'admin_settings.users.welcome_email_is_enabled_help' => '用户完成注册时发送欢迎邮件。',
    'admin_settings.users.email_confirmation' => '邮件确认',
    'admin_settings.users.email_confirmation_help' => '用户注册或更改其电子邮件地址时发送邮件确认。',
    'admin_settings.users.register_is_enabled' => '启用新用户注册',
    'admin_settings.users.register_is_enabled_help' => '允许人们在您的平台上注册或完全禁用注册页面。',
    'admin_settings.users.register_only_social_logins' => '仅限社交登录/注册',
    'admin_settings.users.register_only_social_logins_help' => '如果您只想允许用户使用社交登录进行注册/登录，请启用此项。',
    'admin_settings.users.register_social_login_require_password' => '社交登录注册需要密码',
    'admin_settings.users.register_social_login_require_password_help' => '如果您希望用户在首次通过社交登录注册时必须设置帐户密码，请启用此项。',
    'admin_settings.users.register_display_newsletter_checkbox' => '在注册页面显示新闻通讯订阅复选框',
    'admin_settings.users.account_display_newsletter_checkbox' => '在帐户设置页面显示新闻通讯订阅复选框',
    'admin_settings.users.login_rememberme_checkbox_is_checked' => '在登录页面自动勾选“记住我”',
    'admin_settings.users.login_rememberme_cookie_days' => '“记住我” cookie 时间范围',
    'admin_settings.users.auto_delete_unconfirmed_users' => '自动删除未确认用户',
    'admin_settings.users.auto_delete_unconfirmed_users_help' => '用户如果未确认，将在多少天后被删除，由于是未确认用户，不会发送提醒。设置为0以禁用此功能。',
    'admin_settings.users.auto_delete_inactive_users' => '自动删除不活跃用户',
    'admin_settings.users.auto_delete_inactive_users_help' => '用户如果不活跃（仅对免费用户有效），将在多少天后被删除。设置为0以禁用此功能。',
    'admin_settings.users.user_deletion_reminder' => '用户删除提醒',
    'admin_settings.users.user_deletion_reminder_help' => '在用户因不活跃将被删除前多少天提醒用户。设置为0以禁用提醒。',
    'admin_settings.users.blacklisted_domains' => '黑名单域名',
    'admin_settings.users.blacklisted_domains_help' => '逗号分隔的域名值 ( word1, word2, word3 ..等 )。人们将无法使用此列表中的任何域名进行注册。',
    'admin_settings.users.blacklisted_countries' => '选择黑名单国家',
    'admin_settings.users.blacklisted_countries_help' => '选择您要列入黑名单的国家，禁止其注册到系统。检测基于IP。',
    'admin_settings.users.lockouts' => '反垃圾邮件措施',
    'admin_settings.users.login_lockout_is_enabled' => '启用登录锁定',
    'admin_settings.users.login_lockout_max_retries' => '最大登录重试次数',
    'admin_settings.users.login_lockout_time' => '锁定时长',
    'admin_settings.users.lost_password_lockout_is_enabled' => '启用密码重置锁定',
    'admin_settings.users.lost_password_lockout_max_retries' => '最大重置重试次数',
    'admin_settings.users.lost_password_lockout_time' => '锁定时长',
    'admin_settings.users.resend_activation_lockout_is_enabled' => '启用重发激活邮件锁定',
    'admin_settings.users.resend_activation_lockout_max_retries' => '最大重发重试次数',
    'admin_settings.users.resend_activation_lockout_time' => '锁定时长',
    'admin_settings.users.register_lockout_is_enabled' => '启用注册锁定',
    'admin_settings.users.register_lockout_max_registrations' => '最大注册次数',
    'admin_settings.users.register_lockout_time' => '锁定时长',

    'admin_settings.content.tab' => '内容',
    'admin_settings.content.blog' => '博客',
    'admin_settings.content.blog_is_enabled' => '启用博客系统',
    'admin_settings.content.blog_share_is_enabled' => '启用博客分享文章按钮',
    'admin_settings.content.blog_search_widget_is_enabled' => '启用博客搜索小部件',
    'admin_settings.content.blog_categories_widget_is_enabled' => '启用博客分类小部件',
    'admin_settings.content.blog_popular_widget_is_enabled' => '启用博客热门文章小部件',
    'admin_settings.content.blog_views_is_enabled' => '启用显示博客浏览次数',
    'admin_settings.content.blog_ratings_is_enabled' => '启用博客评分系统',
    'admin_settings.content.blog_columns' => '博客系统列数',
    'admin_settings.content.pages' => '资源',
    'admin_settings.content.pages_is_enabled' => '启用资源（页面）系统',
    'admin_settings.content.pages_share_is_enabled' => '启用页面分享文章按钮',
    'admin_settings.content.pages_popular_widget_is_enabled' => '启用页面热门文章小部件',
    'admin_settings.content.pages_views_is_enabled' => '启用显示页面浏览次数',

    'admin_settings.payment.tab' => '支付',
    'admin_settings.payment.is_enabled' => '启用支付系统',
    'admin_settings.payment.is_enabled_help' => '禁用支付系统将移除用户升级其帐户或查看任何与支付相关信息的所有选项。',
    'admin_settings.payment.default_payment_frequency' => '默认支付频率',
    'admin_settings.payment.default_payment_type' => '默认支付类型',
    'admin_settings.payment.type' => '启用的支付类型',
    'admin_settings.payment.type_one_time' => '一次性',
    'admin_settings.payment.type_recurring' => '定期',
    'admin_settings.payment.type_both' => '两者',
    'admin_settings.payment.brand_name' => '品牌名称',
    'admin_settings.payment.brand_name_help' => '品牌名称将用于在用户通过支付网关购买时显示品牌。（例如：paypal）',
    'admin_settings.payment.currencies' => '货币',
    'admin_settings.payment.currencies.code' => '货币代码',
    'admin_settings.payment.currencies.code_help' => '支付的货币代码（例如：USD, EUR, CAD）。ISO 4217标准。',
    'admin_settings.payment.currencies.symbol' => '货币符号',
    'admin_settings.payment.currencies.default_payment_processor' => '默认处理器',
    'admin_settings.payment.currencies.default_payment_processor_help' => '确保支付处理器已启用此特定货币代码。',
    'admin_settings.payment.default_currency' => '默认货币',
    'admin_settings.payment.default_currency_help' => '支付的默认货币代码。一旦开始接收付款，请勿更改此值。',
    'admin_settings.payment.codes_is_enabled' => '启用折扣码和可兑换码',
    'admin_settings.payment.codes_is_enabled_help' => '启用折扣码系统将使用户能够在结账前添加从管理面板创建的折扣码。',
    'admin_settings.payment.taxes_and_billing_is_enabled' => '启用税收和账单系统',
    'admin_settings.payment.taxes_and_billing_is_enabled_help' => '启用此功能将要求用户在结账前填写其账单信息，您还可以为每个创建的计划创建税收。',
    'admin_settings.payment.invoice_is_enabled' => '启用发票系统',
    'admin_settings.payment.invoice_is_enabled_help' => '此选项将决定用户是否能够查看其付款的发票。',
    'admin_settings.payment.webhook_url' => 'Webhook URL',
    'admin_settings.payment.mode' => '模式',
    'admin_settings.payment.user_plan_expiry_reminder' => '用户计划到期提醒',
    'admin_settings.payment.user_plan_expiry_reminder_help' => '在用户计划到期前多少天提醒用户。设置为0以禁用提醒。',
    'admin_settings.payment.currency_exchange_api_key' => '货币兑换API密钥',
    'admin_settings.payment.currency_exchange_api_key_help' => '只有在您在网站上使用多种货币时才需要此API密钥。',
    'admin_settings.payment.user_plan_expiry_checker_is_enabled' => '用户计划到期检查器和通知器',
    'admin_settings.payment.user_plan_expiry_checker_is_enabled_help' => '自动检查、移除已到期的计划，并通过Cron作业向停止支付计划的用户发送电子邮件。如果禁用，已到期的计划将在用户登录其帐户时重置。',

    'admin_settings.paypal.tab' => 'Paypal',
    'admin_settings.paypal.is_enabled' => '启用Paypal支付',
    'admin_settings.paypal.client_id' => '客户端ID',
    'admin_settings.paypal.secret' => '密钥',

    'admin_settings.stripe.tab' => 'Stripe',
    'admin_settings.stripe.is_enabled' => '启用Stripe支付',
    'admin_settings.stripe.publishable_key' => '可发布密钥',
    'admin_settings.stripe.secret_key' => '密钥',
    'admin_settings.stripe.webhook_secret' => 'Webhook密钥',

    'admin_settings.offline_payment.tab' => '线下支付',
    'admin_settings.offline_payment.is_enabled' => '启用线下支付',
    'admin_settings.offline_payment.instructions' => '说明',
    'admin_settings.offline_payment.instructions_help' => '用户在提交付款前看到的付款说明。',
    'admin_settings.offline_payment.proof_size_limit' => '上传凭证大小限制',

    'admin_settings.coinbase.tab' => 'Coinbase',
    'admin_settings.coinbase.is_enabled' => '启用Coinbase支付',
    'admin_settings.coinbase.api_key' => 'API密钥',
    'admin_settings.coinbase.webhook_secret' => 'Webhook密钥',

    'admin_settings.payu.tab' => 'PayU',
    'admin_settings.payu.is_enabled' => '启用PayU支付',
    'admin_settings.payu.merchant_pos_id' => '商户POS ID',
    'admin_settings.payu.signature_key' => '签名密钥',
    'admin_settings.payu.oauth_client_id' => 'Oauth客户端ID',
    'admin_settings.payu.oauth_client_secret' => 'Oauth客户端密钥',

    'admin_settings.iyzico.tab' => 'Iyzico',
    'admin_settings.iyzico.is_enabled' => '启用Iyzico支付',
    'admin_settings.iyzico.api_key' => 'API密钥',
    'admin_settings.iyzico.secret_key' => '密钥',

    'admin_settings.paystack.tab' => 'Paystack',
    'admin_settings.paystack.is_enabled' => '启用Paystack支付',
    'admin_settings.paystack.public_key' => '公钥',
    'admin_settings.paystack.secret_key' => '密钥',

    'admin_settings.razorpay.tab' => 'Razorpay',
    'admin_settings.razorpay.is_enabled' => '启用Razorpay支付',
    'admin_settings.razorpay.key_id' => '密钥ID',
    'admin_settings.razorpay.key_secret' => '密钥',
    'admin_settings.razorpay.webhook_secret' => 'Webhook密钥',

    'admin_settings.mollie.tab' => 'Mollie',
    'admin_settings.mollie.is_enabled' => '启用Mollie支付',
    'admin_settings.mollie.api_key' => 'API密钥',

    'admin_settings.yookassa.tab' => 'Yookassa',
    'admin_settings.yookassa.is_enabled' => '启用Yookassa支付',
    'admin_settings.yookassa.shop_id' => '店铺ID',
    'admin_settings.yookassa.secret_key' => '密钥',

    'admin_settings.crypto_com.tab' => 'Crypto.com',
    'admin_settings.crypto_com.is_enabled' => '启用Crypto.com支付',
    'admin_settings.crypto_com.publishable_key' => '可发布密钥',
    'admin_settings.crypto_com.secret_key' => '密钥',
    'admin_settings.crypto_com.webhook_secret' => 'Webhook密钥',

    'admin_settings.paddle.tab' => 'Paddle',
    'admin_settings.paddle.is_enabled' => '启用Paddle支付',
    'admin_settings.paddle.vendor_id' => '供应商ID',
    'admin_settings.paddle.api_key' => 'API密钥',
    'admin_settings.paddle.public_key' => '公钥',

    'admin_settings.mercadopago.tab' => 'MercadoPago',
    'admin_settings.mercadopago.is_enabled' => '启用MercadoPago支付',
    'admin_settings.mercadopago.access_token' => '访问令牌',

    'admin_settings.midtrans.tab' => 'Midtrans',
    'admin_settings.midtrans.is_enabled' => '启用Midtrans支付',
    'admin_settings.midtrans.server_key' => '服务器密钥',

    'admin_settings.flutterwave.tab' => 'Flutterwave',
    'admin_settings.flutterwave.is_enabled' => '启用Flutterwave支付',
    'admin_settings.flutterwave.secret_key' => '密钥',

    'admin_settings.lemonsqueezy.tab' => 'Lemonsqueezy',
    'admin_settings.lemonsqueezy.is_enabled' => '启用Lemonsqueezy支付',
    'admin_settings.lemonsqueezy.api_key' => 'API密钥',
    'admin_settings.lemonsqueezy.signing_secret' => '签名密钥',
    'admin_settings.lemonsqueezy.store_id' => '店铺ID',
    'admin_settings.lemonsqueezy.one_time_monthly_variant_id' => '一次性支付 - 每月 - 变体ID',
    'admin_settings.lemonsqueezy.one_time_quarterly_variant_id' => '一次性支付 - 每季 - 变体ID',
    'admin_settings.lemonsqueezy.one_time_biannual_variant_id' => '一次性支付 - 半年 - 变体ID',
    'admin_settings.lemonsqueezy.one_time_annual_variant_id' => '一次性支付 - 每年 - 变体ID',
    'admin_settings.lemonsqueezy.one_time_lifetime_variant_id' => '一次性支付 - 终身 - 变体ID',
    'admin_settings.lemonsqueezy.recurring_monthly_variant_id' => '定期支付 - 每月 - 变体ID',
    'admin_settings.lemonsqueezy.recurring_quarterly_variant_id' => '定期支付 - 每季 - 变体ID',
    'admin_settings.lemonsqueezy.recurring_biannual_variant_id' => '定期支付 - 半年 - 变体ID',
    'admin_settings.lemonsqueezy.recurring_annual_variant_id' => '定期支付 - 每年 - 变体ID',

    'admin_settings.myfatoorah.tab' => 'Myfatoorah',
    'admin_settings.myfatoorah.is_enabled' => '启用Myfatoorah支付',
    'admin_settings.myfatoorah.api_key' => 'API密钥',
    'admin_settings.myfatoorah.secret_key' => '密钥',
    'admin_settings.myfatoorah.api_endpoint' => 'API端点',
    'admin_settings.myfatoorah.api_endpoint_help' => '根据账户地区选择端点。',

    'admin_settings.affiliate.tab' => '联盟',
    'admin_settings.affiliate.is_enabled' => '启用联盟系统',
    'admin_settings.affiliate.is_enabled_help' => '联盟系统将使您的用户能够通过为您的平台带来其他付费用户而获得报酬。',
    'admin_settings.affiliate.commission_type' => '佣金类型',
    'admin_settings.affiliate.commission_type_once' => '一次性 - 为推荐用户的首次付款支付佣金',
    'admin_settings.affiliate.commission_type_forever' => '永久 - 为推荐用户的所有付款支付佣金',
    'admin_settings.affiliate.tracking_type' => '跟踪类型',
    'admin_settings.affiliate.tracking_type_first' => '首次 - 跟踪首次推荐人，直到跟踪持续时间到期',
    'admin_settings.affiliate.tracking_type_last' => '最后 - 将跟踪cookie覆盖为最后一次推荐',
    'admin_settings.affiliate.tracking_duration' => '跟踪持续时间',
    'admin_settings.affiliate.tracking_duration_help' => '联盟跟踪cookie在浏览器中存活多长时间。',
    'admin_settings.affiliate.minimum_withdrawal_amount' => '最低提款金额',
    'admin_settings.affiliate.minimum_withdrawal_amount_help' => '用户需要有多少余额才能请求提款。',
    'admin_settings.affiliate.withdrawal_notes' => '提款请求说明',
    'admin_settings.affiliate.withdrawal_notes_help' => '告知您的用户提款流程。例如，您可以要求他们填写银行账户或Paypal电子邮件。',

    'admin_settings.business.tab' => '商业详情',
    'admin_settings.business.subheader' => '这些详情将用于支付和发票。',
    'admin_settings.business.brand_name' => '品牌名称',
    'admin_settings.business.invoice_nr_prefix' => '发票号前缀',
    'admin_settings.business.invoice_nr_prefix_help' => '您系统中生成的所有发票的编号前缀。例如：INV-',
    'admin_settings.business.name' => '名称',
    'admin_settings.business.address' => '地址',
    'admin_settings.business.county' => '县/区',
    'admin_settings.business.zip' => '邮政编码',
    'admin_settings.business.phone' => '电话',
    'admin_settings.business.tax_type' => '税种',
    'admin_settings.business.tax_type_placeholder' => '例如：VAT',
    'admin_settings.business.tax_id' => '税号',
    'admin_settings.business.custom_key' => '自定义字段名称',
    'admin_settings.business.custom_value' => '自定义字段值',

    'admin_settings.captcha.tab' => '验证码',
    'admin_settings.captcha.type' => '验证码提供商',
    'admin_settings.captcha.type.basic' => '基本验证码（自托管）',
    'admin_settings.captcha.type.recaptcha' => 'Google ReCaptcha v2复选框',
    'admin_settings.captcha.type.hcaptcha' => 'hCaptcha',
    'admin_settings.captcha.type.turnstile' => 'Cloudflare Turnstile',
    'admin_settings.captcha.recaptcha_public_key' => 'ReCaptcha公钥',
    'admin_settings.captcha.recaptcha_private_key' => 'ReCaptcha私钥',
    'admin_settings.captcha.hcaptcha_site_key' => 'hCaptcha网站密钥',
    'admin_settings.captcha.hcaptcha_secret_key' => 'hCaptcha密钥',
    'admin_settings.captcha.turnstile_site_key' => 'Turnstile网站密钥',
    'admin_settings.captcha.turnstile_secret_key' => 'Turnstile密钥',
    'admin_settings.captcha.login_is_enabled' => '在登录页面启用验证码',
    'admin_settings.captcha.register_is_enabled' => '在注册页面启用验证码',
    'admin_settings.captcha.lost_password_is_enabled' => '在忘记密码页面启用验证码',
    'admin_settings.captcha.resend_activation_is_enabled' => '在重发激活页面启用验证码',
    'admin_settings.captcha.contact_is_enabled' => '在联系页面启用验证码',

    'admin_settings.facebook.tab' => 'Facebook登录',
    'admin_settings.facebook.is_enabled' => '启用Facebook登录',
    'admin_settings.facebook.app_id' => '应用ID',
    'admin_settings.facebook.app_secret' => '应用密钥',

    'admin_settings.google.tab' => 'Google登录',
    'admin_settings.google.is_enabled' => '启用Google登录',
    'admin_settings.google.client_id' => '客户端ID',
    'admin_settings.google.client_secret' => '客户端密钥',

    'admin_settings.twitter.tab' => 'X登录',
    'admin_settings.twitter.is_enabled' => '启用X登录',
    'admin_settings.twitter.consumer_api_key' => '消费者API密钥',
    'admin_settings.twitter.consumer_api_secret' => '消费者API密钥',

    'admin_settings.discord.tab' => 'Discord登录',
    'admin_settings.discord.is_enabled' => '启用Discord登录',
    'admin_settings.discord.client_id' => '客户端ID',
    'admin_settings.discord.client_secret' => '客户端密钥',

    'admin_settings.linkedin.tab' => 'LinkedIn登录',
    'admin_settings.linkedin.is_enabled' => '启用LinkedIn登录',
    'admin_settings.linkedin.client_id' => '客户端ID',
    'admin_settings.linkedin.client_secret' => '客户端密钥',

    'admin_settings.microsoft.tab' => 'Microsoft登录',
    'admin_settings.microsoft.is_enabled' => '启用Microsoft登录',
    'admin_settings.microsoft.client_id' => '客户端ID',
    'admin_settings.microsoft.client_secret' => '客户端密钥',

    'admin_settings.cookie_consent.tab' => 'Cookie同意',
    'admin_settings.cookie_consent.is_enabled' => '启用Cookie同意',
    'admin_settings.cookie_consent.is_enabled_help' => 'Cookie同意是通过 <a href="https://github.com/orestbida/cookieconsent" target="_blank">orestbida/cookieconsent</a> 库实现的。如果您添加自己的自定义js并希望它与此一起工作，请阅读他们的文档。',
    'admin_settings.cookie_consent.logging_is_enabled' => '启用日志记录',
    'admin_settings.cookie_consent.logging_is_enabled_help' => '启用此项将把所有用户及其选择的cookie同意偏好记录到一个CSV文件中。',
    'admin_settings.cookie_consent.logging_download' => '下载同意日志',
    'admin_settings.cookie_consent.necessary_is_enabled' => '绝对必要的Cookie',
    'admin_settings.cookie_consent.analytics_is_enabled' => '性能和分析Cookie',
    'admin_settings.cookie_consent.targeting_is_enabled' => '广告和定向Cookie',
    'admin_settings.cookie_consent.layout' => '布局类型',
    'admin_settings.cookie_consent.position_y' => 'Y轴位置',
    'admin_settings.cookie_consent.position_x' => 'X轴位置',

    'admin_settings.socials.tab' => '社交',
    'admin_settings.socials.footer' => '页脚社交',
    'admin_settings.socials.share_buttons' => '分享按钮',
    'admin_settings.socials.enabled_share_buttons' => '启用的分享按钮',

    'admin_settings.smtp.tab' => 'SMTP (电子邮件)',
    'admin_settings.smtp.host' => '主机',
    'admin_settings.smtp.host_help' => '如果此字段中没有输入值，则系统将尝试使用默认的邮件功能。',
    'admin_settings.smtp.from' => '发件人邮箱',
    'admin_settings.smtp.from_help' => '发件人的电子邮件。',
    'admin_settings.smtp.from_name' => '发件人名称',
    'admin_settings.smtp.from_name_help' => '发件人的名称。',
    'admin_settings.smtp.reply_to' => '回复邮箱',
    'admin_settings.smtp.reply_to_help' => '接收者将用于回复的电子邮件地址。',
    'admin_settings.smtp.reply_to_name' => '回复名称',
    'admin_settings.smtp.reply_to_name_help' => '回复电子邮件的名称。',
    'admin_settings.smtp.cc' => '抄送邮箱',
    'admin_settings.smtp.cc_help' => '每封发出的邮件都将抄送至上述电子邮件地址。逗号分隔的值。',
    'admin_settings.smtp.bcc' => '密送邮箱',
    'admin_settings.smtp.bcc_help' => '每封发出的邮件都将密送至上述电子邮件地址。逗号分隔的值。',
    'admin_settings.smtp.encryption' => '加密',
    'admin_settings.smtp.port' => '端口',
    'admin_settings.smtp.auth' => '认证',
    'admin_settings.smtp.username' => '用户名',
    'admin_settings.smtp.password' => '密码',
    'admin_settings.smtp.display_socials' => '显示社交链接',
    'admin_settings.smtp.display_socials_help' => '在所有发送的邮件页脚显示社交媒体图标和链接。',
    'admin_settings.smtp.company_details' => '公司详情',
    'admin_settings.smtp.company_details_help' => '您公司的法律详情，例如：名称、地址、联系方式等。',
    'admin_settings.smtp.theme' => '主题',
    'admin_settings.smtp.button_background_color' => '按钮背景颜色',
    'admin_settings.smtp.button_text_color' => '按钮文本颜色',
    'admin_settings.smtp.button_border_radius' => '按钮边框半径',
    'admin_settings.smtp.main_container_border_radius' => '主容器边框半径',

    'admin_settings.theme.tab' => '主题',
    'admin_settings.theme.advanced_coloring' => '自定义',
    'admin_settings.theme.light' => '浅色主题',
    'admin_settings.theme.dark' => '深色主题',
    'admin_settings.theme.primary_theme' => '主色调主题',
    'admin_settings.theme.primary' => '主色调 - 从浅到深',
    'admin_settings.theme.primary_help' => '您可以从 <a href="https://tailwindcss.com/docs/customizing-colors" target="_blank" rel="nofollow noreferrer">Tailwind颜色调色板</a> 中检查和选择已创建的色调。',
    'admin_settings.theme.gray_theme' => '灰色调主题',
    'admin_settings.theme.gray' => '灰色调 - 从浅到深',
    'admin_settings.theme.gray_help' => '您可以从 <a href="https://tailwindcss.com/docs/customizing-colors" target="_blank" rel="nofollow noreferrer">Tailwind颜色调色板</a> 中检查和选择已创建的色调。选择一个灰色调色板。',
    'admin_settings.theme.others' => '其他设置',
    'admin_settings.theme.border_radius' => '边框半径',
    'admin_settings.theme.font_family' => '字体家族',
    'admin_settings.theme.font_family_help' => 'CSS字体家族名称（例如：Times New Roman）。',
    'admin_settings.theme.font_family_default' => '默认',
    'admin_settings.theme.font_family_custom' => '自定义',

    'admin_settings.custom.tab' => '自定义 JS / CSS',
    'admin_settings.custom.body_content' => '应用主体内容',
    'admin_settings.custom.body_content_help' => '在 <body> 标签内插入自定义代码。例如，用于不同形式的跟踪、Google Tag Manager。',
    'admin_settings.custom.welcome_js' => '用户欢迎JS',
    'admin_settings.custom.welcome_js_help' => '插入您希望在新注册用户首次登录时运行的自定义JS代码。',
    'admin_settings.custom.pay_thank_you_js' => '用户支付感谢JS',
    'admin_settings.custom.pay_thank_you_js_help' => '插入您希望在用户成功支付后的感谢页面上运行的自定义JS代码。',
    'admin_settings.custom.head_js' => '应用自定义JS',
    'admin_settings.custom.head_js_help' => '在您的应用程序中插入自定义JS代码（跟踪代码、聊天脚本等...）。',
    'admin_settings.custom.head_css' => '应用自定义CSS',
    'admin_settings.custom.head_css_help' => '添加自定义CSS以根据需要修改和增强网站的特定样式元素。',

    'admin_settings.custom_images.tab' => '自定义图片',
    'admin_settings.custom_images.info' => '用您自己的图片替换主页的默认图片。',

    'admin_settings.announcements.tab' => '公告',
    'admin_settings.announcements.guests' => '访客',
    'admin_settings.announcements.users' => '用户',
    'admin_settings.announcements.content' => '公告内容',
    'admin_settings.announcements.content_help' => '此字段接受文本、html或javascript。',
    'admin_settings.announcements.text_color' => '文本颜色',
    'admin_settings.announcements.background_color' => '背景颜色',

    'admin_settings.internal_notifications.tab' => '内部通知',
    'admin_settings.internal_notifications.users_is_enabled' => '为用户启用通知系统',
    'admin_settings.internal_notifications.admins_is_enabled' => '为管理员启用通知系统（管理面板）',
    'admin_settings.internal_notifications.new_user' => '新用户',
    'admin_settings.internal_notifications.delete_user' => '已删除用户',
    'admin_settings.internal_notifications.new_payment' => '新付款',
    'admin_settings.internal_notifications.new_affiliate_withdrawal' => '新联盟提款',
    'admin_settings.internal_notifications.new_newsletter_subscriber' => '新新闻通讯订阅者',

    'admin_settings.email_notifications.tab' => '邮件通知',
    'admin_settings.email_notifications.emails' => '要通知的邮箱',
    'admin_settings.email_notifications.emails_help' => '当以下操作之一执行时，将收到通知的电子邮件。添加由逗号分隔的有效电子邮件地址。',
    'admin_settings.email_notifications.new_user' => '新用户',
    'admin_settings.email_notifications.new_user_help' => '当新用户注册到网站时接收邮件。',
    'admin_settings.email_notifications.delete_user' => '删除用户',
    'admin_settings.email_notifications.delete_user_help' => '当任何用户删除其帐户时接收邮件。',
    'admin_settings.email_notifications.new_payment' => '新付款',
    'admin_settings.email_notifications.new_payment_help' => '当新付款成功处理时接收邮件。',
    'admin_settings.email_notifications.new_domain' => '新自定义域名',
    'admin_settings.email_notifications.new_domain_help' => '当新自定义域名等待批准时接收邮件。',
    'admin_settings.email_notifications.contact' => '联系页面邮件',
    'admin_settings.email_notifications.contact_help' => '启用联系系统。',
    'admin_settings.email_notifications.new_affiliate_withdrawal' => '新联盟提款',
    'admin_settings.email_notifications.new_affiliate_withdrawal_help' => '当提交新的联盟提款请求时接收邮件。',

    'admin_settings.push_notifications.tab' => '推送通知',
    'admin_settings.push_notifications.is_enabled' => '启用推送通知系统',
    'admin_settings.push_notifications.guests_is_enabled' => '接受访客作为订阅者',
    'admin_settings.push_notifications.guests_is_enabled_help' => '接受未注册的帐户订阅您的推送通知。',
    'admin_settings.push_notifications.ask_to_subscribe_is_enabled' => '请求用户订阅的弹窗',
    'admin_settings.push_notifications.ask_to_subscribe_is_enabled_help' => '如果用户尚未被请求，将会弹出一个窗口请求用户订阅。否则，他们可以通过页脚链接触发该弹窗。',
    'admin_settings.push_notifications.ask_to_subscribe_delay' => '弹窗显示延迟',
    'admin_settings.push_notifications.ask_to_subscribe_delay_minimum_pageviews_count' => '弹窗显示前的最小会话页面浏览量',
    'admin_settings.push_notifications.pageviews' => '页面浏览量',
    'admin_settings.push_notifications.icon' => '图标',
    'admin_settings.push_notifications.notifications_per_cron' => '每个cron运行发送的总通知数',
    'admin_settings.push_notifications.notifications_per_cron_batch' => '每个cron运行在一个批次中发送的通知数',
    'admin_settings.push_notifications.notifications_per_cron_batch_concurrently' => '每个cron批次同时发送的通知数',

    'admin_settings.offload.tab' => '卸载 & CDN',
    'admin_settings.offload.cdn' => 'CDN',
    'admin_settings.offload.offload' => '卸载',
    'admin_settings.offload.cdn_assets_url' => 'CDN资源URL',
    'admin_settings.offload.cdn_uploads_url' => 'CDN上传URL',
    'admin_settings.offload.cdn_url_help' => '如果您希望为卸载或未卸载的资源也使用CDN，则为CDN基础URL。留空以不使用CDN。',
    'admin_settings.offload.cdn_origin_url' => 'CDN源URL',
    'admin_settings.offload.cdn_origin_url_help' => '您应该在CDN提供商中使用的基础URL，以便CDN从中拉取数据。',
    'admin_settings.offload.assets_url' => '资源URL',
    'admin_settings.offload.assets_url_help' => '指向任何存储提供商（如：Amazon S3, DigitalOcean Spaces）的资源文件夹的完整URL。留空以禁用资源卸载。',
    'admin_settings.offload.provider' => '存储提供商',
    'admin_settings.offload.uploads_url' => '上传URL',
    'admin_settings.offload.uploads_url_help' => '指向任何存储提供商（如：Amazon S3, DigitalOcean Spaces）的上传文件夹的完整URL。留空以禁用文件上传卸载。',
    'admin_settings.offload.endpoint_url' => '端点URL',
    'admin_settings.offload.access_key' => '访问密钥',
    'admin_settings.offload.secret_access_key' => '秘密访问密钥',
    'admin_settings.offload.storage_name' => '存储桶名称',
    'admin_settings.offload.region' => '地区',

    'admin_settings.pwa.tab' => 'PWA',
    'admin_settings.pwa.is_enabled' => '启用PWA系统',
    'admin_settings.pwa.display_install_bar' => '在页脚显示安装助手栏',
    'admin_settings.pwa.display_install_bar_for_guests' => '为访客显示安装栏',
    'admin_settings.pwa.display_install_bar_delay' => '安装栏显示延迟',
    'admin_settings.pwa.display_install_bar_minimum_pageviews_count' => '安装栏显示前的最小会话页面浏览量',
    'admin_settings.pwa.pageviews' => '页面浏览量',
    'admin_settings.pwa.app_name' => '应用名称',
    'admin_settings.pwa.app_name_help' => '您的PWA应用的完整名称 - 将显示在您的手机主屏幕或桌面上。',
    'admin_settings.pwa.app_short_name' => '应用简称',
    'admin_settings.pwa.app_short_name_help' => 'PWA的可选简称 - 当没有足够空间显示完整名称时将显示。',
    'admin_settings.pwa.app_description' => '应用简短描述',
    'admin_settings.pwa.app_description_help' => 'PWA的可选简短描述 - 将在某些设备上安装时和安装后显示。',
    'admin_settings.pwa.background_color' => '背景颜色',
    'admin_settings.pwa.background_color_help' => '启动屏幕和应用加载时使用的背景颜色。',
    'admin_settings.pwa.theme_color' => '主题颜色',
    'admin_settings.pwa.theme_color_help' => '与您应用主题匹配的浏览器UI颜色。',
    'admin_settings.pwa.app_icon' => '应用图标',
    'admin_settings.pwa.app_icon_help' => '确保图标为512x512像素。',
    'admin_settings.pwa.app_icon_maskable' => '可遮罩应用图标',
    'admin_settings.pwa.app_icon_maskable_help' => '确保图标为512x512像素。<a href="https://web.dev/articles/maskable-icon" target="_blank">什么是可遮罩图标？</a>',
    'admin_settings.pwa.mobile_screenshots' => '移动端截图',
    'admin_settings.pwa.mobile_screenshots_help' => '这些截图将在手机上的安装提示中显示，这些是可选的。',
    'admin_settings.pwa.mobile_screenshots_help2' => '所有移动端截图必须具有相同的尺寸。',
    'admin_settings.pwa.desktop_screenshots' => '桌面端截图',
    'admin_settings.pwa.desktop_screenshots_help' => '这些截图将在桌面端的安装提示中显示，这些是可选的。',
    'admin_settings.pwa.desktop_screenshots_help2' => '所有桌面端截图必须具有相同的尺寸。',
    'admin_settings.pwa.screenshot_x' => '截图 %s',
    'admin_settings.pwa.shortcuts' => '快捷方式',
    'admin_settings.pwa.shortcut_name_x' => '快捷方式 #%s - 名称',
    'admin_settings.pwa.shortcut_description_x' => '快捷方式 #%s - 描述',
    'admin_settings.pwa.shortcut_url_x' => '快捷方式 #%s - URL',
    'admin_settings.pwa.shortcut_icon_x' => '快捷方式 #%s - 图标',
    'admin_settings.pwa.shortcut_icon_x_help' => '确保图标为192x192像素。',
    'admin_settings.pwa.app_start_url' => '应用启动URL',
    'admin_settings.pwa.app_start_url_help' => '当PWA应用打开时应加载哪个内部页面。UTM跟踪参数会自动添加：<code>utm_source=pwa&utm_medium=web-app&utm_campaign=install-or-pwa-launch</code>',

    'admin_settings.image_optimizer.tab' => '图片优化器',
    'admin_settings.image_optimizer.is_enabled' => '启用图片优化器系统',
    'admin_settings.image_optimizer.provider' => '优化提供商',
    'admin_settings.image_optimizer.provider.local' => '本地',
    'admin_settings.image_optimizer.provider.local_help' => '基本的本地图片优化。仅适用于JPG文件。',
    'admin_settings.image_optimizer.provider.resmushit' => 'ReSmushIt API',
    'admin_settings.image_optimizer.provider.resmushit_help' => '由ReSmush.It提供的免费外部API。仅适用于最大5MB的JPG、PNG、GIF文件。',
    'admin_settings.image_optimizer.provider.imagerypro' => 'AltumCode Imagery Pro',
    'admin_settings.image_optimizer.provider.imagerypro_help' => '由AltumCode提供的服务。适用于最大20MB的JPG、PNG、SVG、GIF、AVIF、WEBP文件。',
    'admin_settings.image_optimizer.provider.imagerypro_help2' => '订阅任何<a href="https://altumco.de/subscribe-club" target="_blank">AltumCode Club</a>订阅以获取访问权限。',
    'admin_settings.image_optimizer.imagerypro_api_key' => 'API密钥',
    'admin_settings.image_optimizer.imagerypro_api_key_help' => '来自您有效的AltumCode Club订阅的许可证密钥。',
    'admin_settings.image_optimizer.quality' => '优化质量',
    'admin_settings.image_optimizer.quality_help' => '优化后的质量水平。使用~75%可以获得良好的优化结果，并保持良好的质量。',

    'admin_settings.dynamic_og_images.tab' => '动态OG图片',
    'admin_settings.dynamic_og_images.info' => '您必须确保您的服务器不阻止来自以下IP的传入请求：<strong>178.156.142.190</strong>',
    'admin_settings.dynamic_og_images.is_enabled' => '启用动态OG图片生成器系统',
    'admin_settings.dynamic_og_images.preview' => '预览',
    'admin_settings.dynamic_og_images.preview_help' => '这是一个带有示例截图图片的近似预览。实际的动态图片将根据访问的公共页面生成。',
    'admin_settings.dynamic_og_images.api_key' => 'API密钥',
    'admin_settings.dynamic_og_images.api_key_help' => '网站主管理员帐户的API密钥。',
    'admin_settings.dynamic_og_images.imagerypro_api_key' => 'Imagery Pro API密钥',
    'admin_settings.dynamic_og_images.imagerypro_api_key_help' => '来自您有效的AltumCode Club订阅的许可证密钥。',
    'admin_settings.dynamic_og_images.imagerypro_api_key_help2' => '订阅任何<a href="https://altumco.de/subscribe-club" target="_blank">AltumCode Club</a>订阅以获取访问权限。',
    'admin_settings.dynamic_og_images.quality' => '图片质量',
    'admin_settings.dynamic_og_images.quality_help' => '使用~90以获得清晰但仍然小巧且优化的现代WEBP格式图片。',
    'admin_settings.dynamic_og_images.logo' => '徽标',
    'admin_settings.dynamic_og_images.logo_help' => '要在OG图片上显示的徽标。强烈推荐低文件大小的SVG或WEBP。',
    'admin_settings.dynamic_og_images.title' => '标题',
    'admin_settings.dynamic_og_images.title_help' => '您网站的品牌标题，将显示在OG图片上。留空以禁用。',
    'admin_settings.dynamic_og_images.title_color' => '标题颜色',
    'admin_settings.dynamic_og_images.background' => '背景图片',
    'admin_settings.dynamic_og_images.background_help' => '背景图片应为较宽的图片，最好是1200x630。强烈推荐低文件大小的SVG或WEBP。',
    'admin_settings.dynamic_og_images.background_color' => '背景颜色',
    'admin_settings.dynamic_og_images.background_color_help' => '如果背景图片具有透明度或未提供，则将显示背景颜色。',
    'admin_settings.dynamic_og_images.screenshot_image_border_radius' => '截图图片大小边框半径',
    'admin_settings.dynamic_og_images.screenshot_image_border_radius_help' => 'OG图片内动态截图的圆度。',
    'admin_settings.dynamic_og_images.refresh_interval' => '刷新间隔',


    'admin_settings.sso.tab' => 'SSO',
    'admin_settings.sso.is_enabled' => '启用SSO（单点登录）系统',
    'admin_settings.sso.is_enabled_help' => '此功能允许您连接其他AltumCode软件的安装，并允许您的用户通过单击按钮轻松地在它们之间切换。',
    'admin_settings.sso.display_menu_items' => '在菜单中显示切换链接',
    'admin_settings.sso.display_menu_items_help' => '如果启用此项，所有连接网站的链接将显示给您的用户。',
    'admin_settings.sso.display_menu_items_help2' => '如果禁用此项，您可以创建自定义重定向链接并从%s页面%s部分添加它们，URL如下：%s。',
    'admin_settings.sso.display_menu_items_help3' => '<code>{website_id}</code> - 应替换为您在下面输入的网站ID。',
    'admin_settings.sso.display_menu_items_help4' => '<code>{page}</code> - 可以是该特定网站的页面，例如：dashboard。',
    'admin_settings.sso.websites' => '网站',
    'admin_settings.sso.id' => 'ID',
    'admin_settings.sso.id_help' => '网站的简单标识名称。',
    'admin_settings.sso.api_key' => 'API密钥',
    'admin_settings.sso.api_key_help' => '网站主管理员帐户的API密钥。',
    'admin_settings.sso.url_help' => '另一个AltumCode软件安装的基础URL。',

    'admin_settings.webhooks.tab' => 'Webhooks',
    'admin_settings.webhooks.help' => '当此事件触发时，向上述URL发送一个带有%s表单数据值的webhook POST请求。',
    'admin_settings.webhooks.user_new' => '新用户事件 - webhook URL',
    'admin_settings.webhooks.user_update' => '用户更新事件 - webhook URL',
    'admin_settings.webhooks.user_delete' => '用户删除事件 - webhook URL',
    'admin_settings.webhooks.payment_new' => '新付款事件 - webhook URL',
    'admin_settings.webhooks.code_redeemed' => '代码兑换事件 - webhook URL',
    'admin_settings.webhooks.contact' => '联系表单 - webhook URL',
    'admin_settings.webhooks.cron_start' => 'Cron作业开始 - webhook URL',
    'admin_settings.webhooks.cron_end' => 'Cron作业结束 - webhook URL',
    'admin_settings.webhooks.domain_new' => '新用户域名事件 - webhook URL',
    'admin_settings.webhooks.domain_update' => '更新的用户域名事件 - webhook URL',

    'admin_settings.cron.tab' => 'Cron',
    'admin_settings.cron.settings' => '设置',
    'admin_settings.cron.run_manually' => '通过浏览器手动运行',
    'admin_settings.cron.cron' => '基本cron作业',
    'admin_settings.cron.last_execution' => '上次执行：%s',
    'admin_settings.cron.email_reports' => '分析电子邮件报告cron作业',
    'admin_settings.cron.broadcasts' => '广播cron作业',
    'admin_settings.cron.push_notifications' => '推送通知插件cron作业',
    'admin_settings.cron.cron_settings' => 'Cron设置',
    'admin_settings.cron.cron_settings_help' => '如果您不知道自己在做什么，请不要修改这些值。',

    'admin_settings.health.tab' => '健康状况',
    'admin_settings.health.help' => '此页面检查并显示有关您服务器的信息，并告诉您服务器最低要求是否正常。',

    'admin_settings.cache.tab' => '缓存',
    'admin_settings.cache.is_enabled' => '缓存已启用',
    'admin_settings.cache.help' => '软件使用本地文件缓存来存储和检索频繁访问的数据，以获得更好的性能。可以从产品的<code>index.php</code>文件启用或禁用缓存。',
    'admin_settings.cache.size' => '当前缓存大小',
    'admin_settings.cache.clear' => '清除缓存',

    'admin_settings.license.tab' => '许可证',
    'admin_settings.license.license' => '许可证',
    'admin_settings.license.license_help' => '您购买产品时获得的许可证。',
    'admin_settings.license.type' => '许可证类型',
    'admin_settings.license.new_license' => '新许可证',
    'admin_settings.license.new_license_help' => '如果您不想更改它，请留空。仅当您想将网站许可证更改为新许可证时才使用此字段。',

    'admin_settings.support.tab' => '支持',
    'admin_settings.support.key' => '支持密钥',
    'admin_settings.support.status.active' => '有效。将于 %s 到期。',
    'admin_settings.support.status.active.help' => '您有资格通过 support@altumcode.com 获得支持',
    'admin_settings.support.status.inactive' => '无效。已于 %s 到期。',
    'admin_settings.support.status.inactive.help' => '您不再有资格获得支持。',
    'admin_settings.support.extend' => '延长您的支持',
    'admin_settings.support.new_key' => '新支持密钥',
    'admin_settings.support.new_key_help' => '如果您不想更改它，请留空。',

    'admin_settings.ads.tab' => '广告',
    'admin_settings.ads.ads_help' => '广告仅向没有启用“无广告”计划功能的用户显示。这些字段接受文本、html或javascript。',
    'admin_settings.ads.ad_blocker_detector_is_enabled' => '广告拦截器检测器',
    'admin_settings.ads.ad_blocker_detector_is_enabled_help' => '当检测到广告拦截器时，用户将看到一个要求他禁用广告拦截器的弹窗。',
    'admin_settings.ads.ad_blocker_detector_lock_is_enabled' => '锁定用户直到禁用广告拦截器',
    'admin_settings.ads.ad_blocker_detector_delay' => '锁定前延迟',
    'admin_settings.ads.header' => '应用页眉',
    'admin_settings.ads.footer' => '应用页脚',

    'admin_settings.analytics.tab' => '分析',
    'admin_settings.analytics.example_url' => '示例统计页面URL',
    'admin_settings.analytics.example_url_help' => '在主页上显示示例统计页面按钮。留空以禁用。',
    'admin_settings.analytics.ip_storage_is_enabled' => '启用IP存储',
    'admin_settings.analytics.ip_storage_is_enabled_help' => '启用此功能将使您的用户能够保留和查看其访问者的IP。此选项仅适用于高级跟踪。',
    'admin_settings.analytics.sessions_replays_is_enabled' => '启用会话重放 (BETA)',
    'admin_settings.analytics.sessions_replays_is_enabled_help' => '会话重放是一种更高级的跟踪系统，它试图跟踪用户在页面上所做的一切，并向网站所有者直观地重放该会话。',
    'admin_settings.analytics.sessions_replays_is_enabled_help2' => '此功能可以激活，但必须谨慎使用，因为它可能仍包含错误。',
    'admin_settings.analytics.sessions_replays_is_enabled_help3' => '在某些情况下，如果被跟踪的网站很大，并且您的网络主机不允许发布大量数据，则可能无法正常工作。您当前的 POST_MAX_SIZE 是：%s。',
    'admin_settings.analytics.sessions_replays_minimum_duration' => '会话重放的最小持续时间（以秒为单位）',
    'admin_settings.analytics.sessions_replays_minimum_duration_help' => 'Cronjob将自动删除所有不满足所需持续时间的会话重放。',
    'admin_settings.analytics.sessions_replays_minimum_duration_help2' => 'cron只会在用户不活动24小时后删除重放，以确保会话不再活动。',
    'admin_settings.analytics.websites_heatmaps_is_enabled' => '启用热图 (BETA)',
    'admin_settings.analytics.websites_heatmaps_is_enabled_help' => '热图使用户能够跟踪特定页面，并根据多人的数据查找这些页面最常用的部分。',
    'admin_settings.analytics.pixel_cache' => '像素缓存',
    'admin_settings.analytics.pixel_cache_help' => '设置为0以禁用像素跟踪代码的缓存。',
    'admin_settings.analytics.pixel_exposed_identifier' => '像素暴露标识符',
    'admin_settings.analytics.pixel_exposed_identifier_help' => '当告诉您的用户如何自定义使用您的跟踪代码时，会使用像素密钥。例如，用于跟踪他们的目标：<code><strong>your_pixel_exposed_identifier</strong>.goal(\'my-goal\');</code>。',
    'admin_settings.analytics.email_reports_is_enabled' => '分析的电子邮件报告系统',
    'admin_settings.analytics.email_reports_is_enabled_weekly' => '每周',
    'admin_settings.analytics.email_reports_is_enabled_monthly' => '每月',
    'admin_settings.analytics.email_reports_is_enabled_help' => '启用电子邮件报告将使您的用户能够获取其网站统计数据的电子邮件报告。',
    'admin_settings.analytics.email_notices_is_enabled' => '在达到计划限制时发送电子邮件',
    'admin_settings.analytics.email_notices_is_enabled_help' => '当用户的网站每月页面浏览量达到计划限制时，向他们发送电子邮件。',
    'admin_settings.analytics.domains_is_enabled' => '启用自定义域名系统',
    'admin_settings.analytics.domains_custom_main_ip' => '您服务器的IP',
    'admin_settings.analytics.domains_custom_main_ip_help' => '添加自定义域名时将显示的IP。留空以显示默认检测到的服务器IP。',
    'admin_settings.analytics.domains_is_enabled_help' => '启用此功能将使您的用户能够添加和使用自定义域名。',
    'admin_settings.analytics.blacklisted_domains' => '黑名单域名',
    'admin_settings.analytics.blacklisted_domains_help' => '人们将无法提交此列表中包含的任何URL域名。逗号分隔的域名值。',

    'admin_settings_send_test_email_modal.header' => '发送测试邮件',
    'admin_settings_send_test_email_modal.success_message' => '我们已将电子邮件命令发送到您的SMTP，且未收到任何错误。',
    'admin_settings_send_test_email_modal.error_message' => '我们已将电子邮件命令发送到您的SMTP，但收到了以下错误：%s',


    'admin_teams.title' => '团队',
    'admin_teams.header' => '团队',
    'admin_teams.menu' => '团队',


    'admin_team_members.title' => '团队成员',
    'admin_team_members.header' => '团队成员',
    'admin_team_members.menu' => '团队成员',


    'admin_teams_member.title' => '团队的成员',
    'admin_teams_member.header' => '团队的成员',
    'admin_teams_member.menu' => '团队的成员',


    'admin_plugins.title' => '插件',
    'admin_plugins.menu' => '插件',
    'admin_plugins.header' => '插件',
    'admin_plugins.header_no_data' => '无可用插件',
    'admin_plugins.subheader_no_data' => '目前没有可用的插件 :(。',
    'admin_plugins.no_access' => '您必须拥有、安装并激活“%s”插件才能使用此功能。',
    'admin_plugins.install' => '安装',
    'admin_plugins.uninstall' => '卸载',
    'admin_plugins.activate' => '激活',
    'admin_plugins.disable' => '禁用',
    'admin_plugins.status_inexistent' => '获取插件',
    'admin_plugins.status_uninstalled' => '已卸载',
    'admin_plugins.status_active' => '活跃',
    'admin_plugins.status_disabled' => '已禁用',
    'admin_plugins.settings' => '设置',
    'admin_plugins.outdated' => '插件已过时<br />最新版本：%s',

    'admin_plugins.table.plugin' => '插件',
    'admin_plugins.table.version' => '版本',
    'admin_plugins.table.author' => '作者',
    'admin_plugins.install_message' => '%s 已成功安装。',
    'admin_plugins.uninstall_message' => '%s 已成功卸载。',
    'admin_plugins.activate_message' => '%s 已成功激活。',
    'admin_plugins.disable_message' => '%s 已成功禁用。',

    'admin_plugin_uninstall_modal.header' => '卸载插件',
    'admin_plugin_uninstall_modal.subheader' => '卸载插件后，所有与该插件相关的潜在数据将从系统中移除。',

    'admin_plugin_delete_modal.header' => '删除插件',
    'admin_plugin_delete_modal.subheader' => '要删除插件，只需进入 <strong>plugins</strong> 文件夹并删除该插件。',


    'admin_languages.breadcrumb' => '语言',
    'admin_languages.title' => '语言',
    'admin_languages.menu' => '语言',
    'admin_languages.header' => '语言',
    'admin_languages.header_no_data' => '无可用语言',
    'admin_languages.main_settings' => '主要设置',
    'admin_languages.translate_app' => '翻译应用',
    'admin_languages.translate_admin' => '翻译管理后台',
    'admin_languages.custom_translations' => '自定义翻译',
    'admin_languages.create_translation' => '创建新翻译',
    'admin_languages.language_key' => '语言键',
    'admin_languages.hide_unused_features' => '隐藏未使用的功能',
    'admin_languages.hide_unused_features_tooltip' => '不显示来自已禁用/未安装插件或功能的翻译。',
    'admin_languages.auto_translate_all' => '自动翻译全部',
    'admin_languages.auto_translate_all_help' => '此按钮将开始逐个翻译每个字段。您可以随时通过单击Escape键停止该过程。',
    'admin_languages.auto_translate' => '自动翻译',
    'admin_languages.auto_translate_help' => '请务必仔细检查翻译结果。',
    'admin_languages.auto_translate_info' => '您必须在设置页面中添加您的OpenAI API密钥才能使用此功能。',
    'admin_languages.language_name' => '语言',
    'admin_languages.language_name_help' => '语言的名称，例如：French, Italian...等。',
    'admin_languages.language_code' => '语言代码',
    'admin_languages.language_code_help' => 'ISO 639-1语言代码，例如：fr, it...等。',
    'admin_languages.language_flag' => '国旗表情符号',
    'admin_languages.language_flag_placeholder' => '🇺🇸',
    'admin_languages.display' => '显示类型',
    'admin_languages.display_translated' => '已翻译',
    'admin_languages.display_not_translated' => '未翻译',
    'admin_languages.main' => '主要语言',
    'admin_languages.default_language' => '默认语言',
    'admin_languages.info_message.max_input_vars' => '您的PHP设置 (max_input_vars) 允许您一次提交 %1$s 个字段。<br /><small>请从您的主机增加此设置，或联系您的虚拟主机提供商请求他们为您更改。</small>',
    'admin_languages.info_message.total' => '当前有 %1$s/%2$s 个已填充的翻译字符串（%3$s 个空的翻译字符串）。',
    'admin_languages.info_message.main' => '主要语言将始终随着新更新的发布而被替换。<a href="' . PRODUCT_DOCUMENTATION_URL . '" target="_blank">阅读文档FAQ</a>。',
    'admin_languages.error_message.language_exists' => '%1$s (%2$s) 语言已存在。',
    'admin_languages.error_message.missing_variables' => '此字段期望 %1$s 个变量字符串，但提供了 %2$s 个。',


    'admin_language_create.breadcrumb' => '创建语言',
    'admin_language_create.title' => '创建语言',
    'admin_language_create.header' => '创建语言',
    'admin_language_create.subheader' => '创建后，您可以翻译新的语言。',
    'admin_language_create.menu' => '创建语言',


    'admin_language_update.breadcrumb' => '编辑语言',
    'admin_language_update.title' => '编辑语言',
    'admin_language_update.header' => '编辑语言',


    'admin_statistics.title' => '统计 - %s',
    'admin_statistics.menu' => '统计',
    'admin_statistics.header' => '统计',
    'admin_statistics.subheader' => '查看您的网站如何随时间演变。',
    'admin_statistics.users' => '用户',
    'admin_statistics.users.header' => '用户',
    'admin_statistics.percentage' => '百分比',

    'admin_statistics.payments' => '付款',
    'admin_statistics.payments.menu' => '付款',
    'admin_statistics.payments.header' => '销售',
    'admin_statistics.payments.chart_total_payments' => '总销售额',
    'admin_statistics.payments.chart_total_amount' => '总收入',
    'admin_statistics.payments.processors' => '支付处理器',
    'admin_statistics.payments.plans' => '支付计划',
    'admin_statistics.payments.types' => '支付类型',
    'admin_statistics.payments.frequencies' => '支付频率',

    'admin_statistics.redeemed_codes.menu' => '已兑换代码',
    'admin_statistics.redeemed_codes.header' => '已兑换代码',
    'admin_statistics.redeemed_codes.chart_discount_codes' => '折扣代码',
    'admin_statistics.redeemed_codes.chart_redeemable_codes' => '可兑换代码',

    'admin_statistics.affiliates_commissions.menu' => '联盟佣金',
    'admin_statistics.affiliates_commissions.header' => '联盟佣金',
    'admin_statistics.affiliates_commissions.chart_total_affiliates_commissions' => '总联盟佣金',
    'admin_statistics.affiliates_commissions.chart_amount' => '总金额',

    'admin_statistics.affiliates_withdrawals.menu' => '联盟提款',
    'admin_statistics.affiliates_withdrawals.header' => '联盟提款',
    'admin_statistics.affiliates_withdrawals.chart_total_affiliates_withdrawals' => '总联盟提款',
    'admin_statistics.affiliates_withdrawals.chart_amount' => '总金额',

    'admin_statistics.database.menu' => '数据库',
    'admin_statistics.database.header' => '数据库',
    'admin_statistics.database.size' => '大小',
    'admin_statistics.database.rows' => '行数',

    'admin_statistics.broadcasts.menu' => '广播',
    'admin_statistics.broadcasts.header' => '新广播',
    'admin_statistics.broadcasts.chart_broadcasts' => '广播',
    'admin_statistics.broadcasts.chart_sent_emails' => '已发送邮件',

    'admin_statistics.internal_notifications.chart_internal_notifications' => '已发送通知',
    'admin_statistics.internal_notifications.chart_read_notifications' => '已读通知',

    'admin_statistics.push_notifications.chart_sent_push_notifications' => '已发送通知',

    'admin_statistics.growth.menu' => '用户增长',
    'admin_statistics.growth.header' => '用户增长',

    'admin_statistics.growth.users.header' => '新注册用户',
    'admin_statistics.growth.users.chart' => '用户',

    'admin_statistics.growth.users_logs.header' => '活跃用户',
    'admin_statistics.growth.users_logs.chart' => '活跃用户',

    'admin_statistics.users_map.menu' => '用户地图',

    'admin_statistics.users.menu' => '用户统计',
    'admin_statistics.users.devices' => '设备',
    'admin_statistics.users.operating_systems' => '操作系统',
    'admin_statistics.users.browsers' => '浏览器',
    'admin_statistics.users.sources' => '来源',
    'admin_statistics.users.source' => '来源',
    'admin_statistics.users.plans' => '计划',
    'admin_statistics.users.plan' => '计划',

    'admin_statistics.websites.menu' => '网站',
    'admin_statistics.websites.header' => '网站',
    'admin_statistics.websites.chart' => '新网站',

    'admin_statistics.lightweight_events.menu' => '轻量级页面浏览',
    'admin_statistics.lightweight_events.header' => '轻量级页面浏览',
    'admin_statistics.lightweight_events.chart' => '轻量级页面浏览',

    'admin_statistics.sessions_events.menu' => '高级页面浏览',
    'admin_statistics.sessions_events.header' => '高级页面浏览',
    'admin_statistics.sessions_events.chart' => '高级页面浏览',

    'admin_statistics.events_children.menu' => '访客事件',
    'admin_statistics.events_children.header' => '访客事件',
    'admin_statistics.events_children.chart_click' => '点击',
    'admin_statistics.events_children.chart_form' => '表单提交',
    'admin_statistics.events_children.chart_scroll' => '滚动事件',
    'admin_statistics.events_children.chart_resize' => '窗口调整大小事件',

    'admin_statistics.sessions_replays.menu' => '会话重放',
    'admin_statistics.sessions_replays.header' => '会话重放',
    'admin_statistics.sessions_replays.chart' => '会话重放',
    'admin_statistics.sessions_replays.chart_total_size' => '总大小',

    'admin_statistics.websites_heatmaps.menu' => '热图',
    'admin_statistics.websites_heatmaps.header' => '热图',
    'admin_statistics.websites_heatmaps.chart' => '热图',
    'admin_statistics.websites_heatmaps.chart_total_size' => '总大小',


    'admin_statistics.websites_goals.menu' => '目标',
    'admin_statistics.websites_goals.header' => '目标',
    'admin_statistics.websites_goals.chart' => '目标',

    'admin_statistics.goals_conversions.menu' => '目标转化',
    'admin_statistics.goals_conversions.header' => '目标转化',
    'admin_statistics.goals_conversions.chart' => '目标转化',

    'admin_statistics.email_reports.menu' => '邮件报告',
    'admin_statistics.email_reports.header' => '邮件报告',
    'admin_statistics.email_reports.chart' => '邮件报告',


    'admin_api_documentation.menu' => 'API文档',
    'admin_api_documentation.title' => '管理员API文档',
    'admin_api_documentation.header' => '管理员API文档',
    'admin_api_documentation.subheader' => '这是仅供管理员使用的可用API端点的文档，它们围绕<strong>REST架构</strong>构建。所有API端点都将返回一个<strong>JSON响应</strong>，带有标准的<strong>HTTP响应代码</strong>，并且需要通过<strong>API密钥进行Bearer认证</strong>。',

    'admin_api_documentation.users.header' => '用户',
    'admin_api_documentation.users.update.status' => '0 - 禁用, 1 - 活跃, 2 - 封禁',
    'admin_api_documentation.users.update.type' => '0 - 普通用户, 1 - 管理员',
    'admin_api_documentation.users.update.plan_id' => '\'free\', 或一个整数plan_id',
    'admin_api_documentation.users.update.plan_expiration_date' => 'Y-m-d H:i:s格式，UTC时区',
    'admin_api_documentation.users.update.plan_trial_done' => '0 - 否, 1 - 是',
    'admin_api_documentation.users.one_time_login_code_header' => '生成一次性登录码',
    'admin_api_documentation.plans.header' => '计划',
    'admin_api_documentation.payments.header' => '付款',
    'admin_api_documentation.domains.header' => '域名',


    'admin_logs.breadcrumb' => '日志',
    'admin_logs.title' => '日志',
    'admin_logs.header' => '日志',
    'admin_logs.menu' => '日志',
    'admin_logs.main.size' => '大小',
    'admin_logs.main.last_modified' => '最后修改',
    'admin_logs.total' => '本月有 %s 个日志文件',


    'admin_log.breadcrumb' => '日志',
    'admin_log.title' => '日志 - %s',
    'admin_log.header' => '%s 日志',


    'admin_broadcasts.breadcrumb' => '广播',
    'admin_broadcasts.title' => '广播',
    'admin_broadcasts.menu' => '广播',
    'admin_broadcasts.header' => '广播',
    'admin_broadcasts.header_no_data' => '创建您的广播',
    'admin_broadcasts.subheader_no_data' => '轻松向您的用户发送您的第一封新闻通讯或营销邮件。',
    'admin_broadcasts.create' => '创建广播',
    'admin_broadcasts.broadcast' => '广播',
    'admin_broadcasts.name_help' => '仅用于内部目的的名称，在电子邮件广播中不公开。',
    'admin_broadcasts.subject' => '主题',
    'admin_broadcasts.subject_help' => '邮件的标题。建议您不要使用超过9个单词/60个字符。',
    'admin_broadcasts.is_system_email' => '是系统邮件',
    'admin_broadcasts.is_system_email_help' => '您的用户将收到该邮件，其目的是作为强制性通知邮件，而不是用于营销（例如隐私政策变更、安全更新等）。',
    'admin_broadcasts.segment' => '分段',
    'admin_broadcasts.segment_help' => '选择您要向其发送邮件的用户组。',
    'admin_broadcasts.segment_help2' => '我们建议您不要向未主动订阅您的新闻通讯的用户发送营销邮件。',
    'admin_broadcasts.segment.all' => '所有用户',
    'admin_broadcasts.segment.subscribers' => '订阅者',
    'admin_broadcasts.segment.custom' => '自定义',
    'admin_broadcasts.segment.filter' => '筛选',
    'admin_broadcasts.segment.filter.is_newsletter_subscribed' => '是否订阅？',
    'admin_broadcasts.segment.filter.plans' => '计划',
    'admin_broadcasts.users_ids' => '用户ID',
    'admin_broadcasts.users_ids_placeholder' => '1,2,3',
    'admin_broadcasts.users_ids_help' => '逗号分隔的值。',
    'admin_broadcasts.content' => '内容',
    'admin_broadcasts.status.draft' => '草稿',
    'admin_broadcasts.status.processing' => '处理中',
    'admin_broadcasts.status.sent' => '已发送',
    'admin_broadcasts.total_emails' => '总邮件数',
    'admin_broadcasts.sent_emails' => '已发送邮件数',
    'admin_broadcasts.views' => '浏览量',
    'admin_broadcasts.clicks' => '点击量',
    'admin_broadcasts.views_tooltip' => '跟踪仅对允许在其邮件中显示图片的用户有效。',
    'admin_broadcasts.last_sent_email_datetime' => '上次发送邮件 %s',
    'admin_broadcasts.latest_views' => '最新浏览',
    'admin_broadcasts.cities_placeholder' => '东京, 纽约, 伊斯坦布尔',
    'admin_broadcasts.cities_help' => '逗号分隔的值。',
    'admin_broadcasts.browser_languages' => '浏览器语言',
    'admin_broadcasts.languages' => '语言',
    'admin_broadcasts.operating_systems' => '操作系统',
    'admin_broadcasts.browsers' => '浏览器',


    'admin_broadcast_create.breadcrumb' => '创建广播',
    'admin_broadcast_create.title' => '创建广播',
    'admin_broadcast_create.menu' => '创建广播',
    'admin_broadcast_create.header' => '创建一个新广播',
    'admin_broadcast_create.content_placeholder' => '您的邮件内容在这里..',
    'admin_broadcast_create.info1' => '您必须首先确保您的SMTP工作正常，并且您的服务器能够处理该过程。',
    'admin_broadcast_create.info2' => '发送批量邮件会给您的服务器带来很大压力，并需要时间来处理。系统每次cron作业运行可以发送30封邮件。',
    'admin_broadcast_create.info3' => '发送大量批量邮件如果被接收者视为垃圾邮件，也可能损害您的域名声誉。',
    'admin_broadcast_create.save_draft' => '保存草稿',
    'admin_broadcast_create.send_preview' => '发送预览',
    'admin_broadcast_create.send_broadcast' => '发送广播',
    'admin_broadcast_create.success_message.preview' => '预览邮件已发送至 %s',
    'admin_broadcast_create.success_message.save' => '%s 广播已保存。您可以稍后回来发送它。',
    'admin_broadcast_create.success_message.send' => '%s 广播将开始处理。',


    'admin_broadcast_update.breadcrumb' => '更新广播',
    'admin_broadcast_update.title' => '更新广播',
    'admin_broadcast_update.menu' => '更新广播',
    'admin_broadcast_update.header' => '更新广播',


    'admin_broadcast_view.breadcrumb' => '查看广播',
    'admin_broadcast_view.title' => '查看广播',
    'admin_broadcast_view.menu' => '查看广播',
    'admin_broadcast_view.header' => '查看广播',


    'admin_dynamic_og_images.breadcrumb' => '动态OG图片',
    'admin_dynamic_og_images.title' => '动态OG图片',
    'admin_dynamic_og_images.header' => '动态OG图片',
    'admin_dynamic_og_images.menu' => '动态OG图片',
    'admin_dynamic_og_images.size' => '大小',
    'admin_dynamic_og_images.last_modified' => '最后修改',
    'admin_dynamic_og_images.pending' => '处理队列中',
    'admin_dynamic_og_images.processed' => '已处理',
    'admin_dynamic_og_images.header_no_data' => '没有可用的动态OG图片。',
    'admin_dynamic_og_images.subheader_no_data' => '系统将在您访问公共页面时自动为其生成动态OG图片。',


    'admin_domains.breadcrumb' => '域名',
    'admin_domains.title' => '域名',
    'admin_domains.header' => '域名',
    'admin_domains.menu' => '域名',
    'admin_domains.table.host' => '域名',

    'admin_domains.helper' => '请确保您的域名或子域名有一个指向 %s 的A记录，或一个指向 %s 的CNAME记录。',
    'admin_domains.scheme' => '协议',
    'admin_domains.host' => '域名或子域名',
    'admin_domains.host_placeholder' => 'domain.com',
    'admin_domains.host_help' => '只允许 <code>domain.com</code> 和 <code>subdomain.domain.com</code> 格式。',
    'admin_domains.dns' => 'DNS值',
    'admin_domains.dns_help' => '这些是当前检测到的DNS值。',
    'admin_domains.custom_index_url' => '自定义索引URL',
    'admin_domains.custom_index_url_help' => '当访问者访问域名的索引页时，重定向到特定URL。',
    'admin_domains.custom_not_found_url' => '自定义404未找到URL',
    'admin_domains.custom_not_found_url_help' => '当访问者访问域名的未找到页面时，重定向到特定URL。',
    'admin_domains.type_global' => '全局域名',
    'admin_domains.type_user' => '用户域名',


    'admin_domain_update.breadcrumb' => '编辑域名',
    'admin_domain_update.title' => '编辑域名',
    'admin_domain_update.header' => '编辑域名',


    'admin_websites.title' => '网站',
    'admin_websites.header' => '网站',
    'admin_websites.menu' => '网站',

    'admin_heatmaps.title' => '热图',
    'admin_heatmaps.header' => '热图',
    'admin_heatmaps.menu' => '热图',

    'admin_replays.title' => '重放',
    'admin_replays.header' => '重放',
    'admin_replays.menu' => '重放',
];